const quotes = {
    "en": {
        0: ["The universe whispers to those who are ready to listen.", "Copilot."],
        1: ["Lightning is not just anger, but the pointing finger of fate.", "Zeus."],
        2: ["Thunder is the voice of the gods, and today it speaks to mortals.", "Zeus."],
        3: ["The gods give signs, but the wise know how to read them.", "Zeus."],
        4: ["To rule the world is to see farther than mortals.", "Zeus."],
        5: ["The secrets of the depths are known to those who dare to plunge into the abyss.", "Poseidon."],
        6: ["The dry land beneath our feet was once part of the ocean.", "Poseidon."],
        7: ["Water is both a creative and destructive force.", "Poseidon."],
        8: ["No one escapes their fate, not even the gods.", "Hades."],
        9: ["The sky hides more shadows than stars.", "Hades."],
        10: ["The memory of the living preserves souls.", "Hades."],
        11: ["Life is a contract with fate that will be dissolved in time.", "Hades."],
        12: ["Fate bows to wisdom, not to rage.", "Athena."],
        13: ["Knowledge is the only power that cannot be taken away.", "Athena."],
        14: ["Chaos destroys itself; order creates eternity.", "Athena."],
        15: ["Do not seek glory in battle if you are not ready to bear its burden.", "Athena."],
        16: ["Freedom belongs to those who are not afraid of solitude.", "Artemis."],
        17: ["The moon hides and reveals the truth.", "Artemis."],
        18: ["He who fears blood has already lost.", "Ares."],
        19: ["There is no peace without war, no victory without pain.", "Ares."],
        20: ["In battle, there is no justice—only the outcome.", "Ares."],
        21: ["The sword does not ask questions; it only answers.", "Ares."],
        22: ["The earth is generous to those who know how to wait.", "Demeter."],
        23: ["Do not lose touch with your roots—they nourish you with the strength of your ancestors.", "Demeter."],
        24: ["Fate is like a harvest: what you sow, so shall you reap.", "Demeter."],
        25: ["Life flows like a river, and everything returns to the beginning.", "Demeter."],
        26: ["Only the dead have seen the end of war.", "Plato."],
        27: ["Fortune favors the prepared.", "Plato."],
        28: ["Thinking is the language the soul speaks to itself.", "Plato."],
        29: ["The highest wisdom is distinguishing good from evil.", "Socrates."],
        30: ["A life without trials is not a life.", "Socrates."],
        31: ["Wisdom is knowing how little we know.", "Socrates."],
        32: ["He who wants to move the world must first move himself.", "Socrates."],
        33: ["Friendship is a single soul dwelling in two bodies.", "Aristotle."],
        34: ["All knowledge begins with wonder.", "Aristotle."],
        35: ["Only he who has known fire understands its true value.", "Hephaestus."],
        36: ["Craftsmanship is not a gift but a test of the spirit.", "Hephaestus."],
        37: ["The world is not built with words but with the strikes of a hammer.", "Hephaestus."],
        38: ["Home is not a place but a state of the soul.", "Hestia."],
        39: ["Warmth does not require strength, only care.", "Hestia."],
        40: ["Without fire, there is no life; without home, there is no happiness.", "Hestia."],
        41: ["Family is not the bonds of blood but the bonds of loyalty.", "Hera."],
        42: ["The wrath of a goddess is like a storm.", "Hera."],
        43: ["Love is not a choice but a decree of the gods.", "Aphrodite."],
        44: ["He who has known love has glimpsed the divine.", "Aphrodite."],
        45: ["You may run from love, but it will always find you.", "Aphrodite."],
        46: ["Beauty is not appearance but a reflection of inner harmony.", "Apollo."],
        47: ["Words can heal or wound.", "Apollo."],
        48: ["He who seeks harmony must first find it within himself.", "Apollo."],
        49: ["If we trust mathematics, we are immortal.", "Sabine Hossenfelder."],
        50: ["Cognitive biases are the greatest problem because people believe they think objectively.", "Sabine Hossenfelder."],
        51: ["Science advances through funerals.", "Sabine Hossenfelder."],
        52: ["The true purpose of life is art.", "Friedrich Nietzsche."],
        53: ["All interesting people are absent in heaven.", "Friedrich Nietzsche."],
        54: ["What does not kill me makes me stronger.", "Friedrich Nietzsche."],
        55: ["The world is an illusion created by a secret conspiracy of our senses.", "Roger Penrose."],
        56: ["The stars do not predict the future—they merely illuminate the paths.", "Vettius Valens."],
        57: ["As above, so below: the movements of the heavens reflect in the soul.", "Hermeticism."],
        58: ["Let the stars be your guides, but not your limits.", "Vettius Valens."],
        59: ["The moon is a mirror of our emotions, changing its face with each cycle.", "Vettius Valens."],
        60: ["Millennia have passed, yet people still seek answers in the patterns of the stars.", "Guido Bonazzi."],
        61: ["The influence of planets is the language of the Universe—one must learn to hear it.", "Guido Bonazzi."],
        62: ["Fate is not carved in stone, but the stars may hint at the roads ahead.", "Guido Bonazzi."],
        63: ["A horoscope is not a prediction but an opportunity to understand oneself deeper.", "William Lilly."],
        64: ["We were born under the stars, but we create our own light.", "Unknown author."],
        65: ["The rising sign is the mask we wear before the world.", "William Lilly."],
        66: ["Each planet dances its own dance, setting the rhythm of our lives.", "William Lilly."],
        67: ["The moon teaches us that emotions come and go like the tides.", "William Lilly."],
        68: ["Retrograde Mercury does not bring chaos—it reminds us of unfinished business.", "Unknown author."],
        69: ["Astrology is the art of reading time, inscribed in the stars.", "Jean-Baptiste Morin."],
        70: ["Each zodiac sign is a story told in light and shadow.", "Jean-Baptiste Morin."],
        71: ["Aries blazes the trail, Libra seeks balance, Pisces swims through dreams.", "Unknown author."],
        72: ["The Universe speaks to us in the whispers of the stars—we must learn to listen.", "Unknown author."],
        73: ["Saturn teaches patience, Venus—love, Jupiter—faith in possibilities.", "Jean-Baptiste Morin."],
        74: ["The stars do not give ready answers; they guide us toward understanding.", "Dorotheus of Sidon."],
        75: ["People look at the sky and see light, but astrologers see destiny.", "Dorotheus of Sidon."],
        76: ["Comets are messengers from the past, carrying secrets of long-forgotten worlds.", "Carl Sagan."],
        77: ["Meteors flash across the sky like the Universe’s memories of what was and what will be.", "Firmicus Maternus."],
        78: ["The new moon is not an end but a promise of a new beginning.", "Firmicus Maternus."],
        79: ["The supermoon reminds us that even the farthest dreams can draw near.", "Firmicus Maternus."],
        80: ["During the full moon, hearts open, and secrets become visible.", "Unknown author."],
        81: ["In a solar eclipse, day and night merge into a single moment.", "Claudius Ptolemy."],
        82: ["When a shooting star streaks the sky, a moment feels like eternity.", "Abu Ma'shar."],
        83: ["Planetary parades are the dance of celestial bodies—cosmic harmony in motion.", "Jean-Baptiste Morin."],
        84: ["A lunar eclipse reveals the struggle between light and darkness in the Universe.", "Guido Bonazzi."],
        85: ["A comet’s flight is a rare reminder that wonders exist even in the void.", "Guido Bonazzi."],
        86: ["Venus rising in the morning sky is a symbol of love awakening in the heart.", "Unknown author."],
        87: ["The zodiac is a map of the soul’s stellar journey through time.", "Vettius Valens."],
        88: ["When the new moon comes, the stars tell stories we have yet to hear.", "Guido Bonazzi."],
        89: ["Meteor showers are rain from ancient messages, glowing in the night.", "Unknown author."],
        90: ["The full moon stirs the hidden depths of the soul, like a tide carrying secret emotions.", "Firmicus Maternus."],
        91: ["Eclipses are signs of change, like pages turned by time.", "Unknown author."],
        92: ["Stars are not just light—they are ancient chronicles written in their rays.", "Unknown author."],
        93: ["Celestial phenomena are signs the Universe leaves for the attentive.", "Unknown author."],
        94: ["The moon converses with the tides, and the whisper of waves is its reply.", "Unknown author."],
        95: ["A great comet is a visitor from the depths of space, a reminder that we are part of something greater.", "Unknown author."],
    },
    "ru": {
        0: ["Вселенная шепчет тем, кто готов её слушать.", "Копилот."],
        1: ["Молния — это не просто гнев, но указующий перст судьбы.", "Зевс."],
        2: ["Гром — голос богов, и сегодня он говорит со смертными.", "Зевс."],
        3: ["Боги дают знаки, но разумные умеют их читать.", "Зевс."],
        4: ["Править миром — значит видеть дальше смертных.", "Зевс."],
        5: ["Тайны глубин известны осмелившимся погрузиться в бездну.", "Посейдон."],
        6: ["Сухая земля под ногами была когда-то частью океана.", "Посейдон."],
        7: ["Вода — созидающая и уничтожающая сила.", "Посейдон."],
        8: ["Никто не избежит своей судьбы, даже боги.", "Аид."],
        9: ["Небо скрывает больше теней, чем звёзд.", "Аид."],
        10: ["Память живых сохраняет души.", "Аид."],
        11: ["Жизнь — договор с судьбой, который расторгнется со временем.", "Аид."],
        12: ["Судьба склоняется перед мудростью, не перед яростью.", "Афина."],
        13: ["Знание — единственная сила, которую нельзя отнять.", "Афина."],
        14: ["Хаос уничтожает себя, порядок создаёт вечность.", "Афина."],
        15: ["Не ищи славу в битве, если не готов нести её бремя.", "Афина."],
        16: ["Свобода принадлежит тем, кто не боится одиночества.", "Артемида."],
        17: ["Луна скрывает и освещает истину.", "Артемида."],
        18: ["Кто боится крови, уже проиграл.", "Арес."],
        19: ["Нет мира без войны, нет победы без боли.", "Арес."],
        20: ["В бою нет справедливости, есть только исход.", "Арес."],
        21: ["Меч не задаёт вопросов, он лишь отвечает.", "Арес."],
        22: ["Земля щедра к тем, кто умеет ждать.", "Деметра."],
        23: ["Не теряй связь с корнями — они питают тебя силой предков.", "Деметра."],
        24: ["Судьба подобна урожаю: что посеешь, то и пожнёшь.", "Деметра."],
        25: ["Жизнь течёт, как река, и все возвращается к началу.", "Деметра."],
        26: ["Конец войны видели только мёртвые.", "Платон."],
        27: ["Судьба благоволит подготовленным.", "Платон."],
        28: ["Мышление — это язык, который душа ведёт с собой.", "Платон."],
        29: ["Высшая мудрость — различать добро и зло.", "Сократ."],
        30: ["Жизнь без испытаний – это не жизнь.", "Сократ."],
        31: ["Мудрость — это знать, насколько мало мы знаем.", "Сократ."],
        32: ["Кто хочет сдвинуть мир, пусть сдвинет себя.", "Сократ."],
        33: ["Дружба — это одна душа, живущая в двух телах.", "Аристотель."],
        34: ["Познание начинается с удивления.", "Аристотель."],
        35: ["Лишь тот, кто познал огонь, знает его истинную цену.", "Гефест."],
        36: ["Ремесло — это не дар, а испытание духа.", "Гефест."],
        37: ["Мир не строится словами, а ударами молота.", "Гефест."],
        38: ["Дом — это не место, а состояние души.", "Гестия."],
        39: ["Тепло не требует силы, лишь заботы.", "Гестия."],
        40: ["Без огня нет жизни, без дома нет счастья.", "Гестия."],
        41: ["Семья — это не узлы крови, а узы верности.", "Гера."],
        42: ["Гнев богини подобен буре.", "Гера."],
        43: ["Любовь — это не выбор, а веление богов.", "Афродита."],
        44: ["Тот, кто познал любовь, увидел божественное.", "Афродита."],
        45: ["Ты можешь бежать от любви, но она всегда найдет тебя.", "Афродита."],
        46: ["Красота — это не внешность, а отражение внутреннего порядка.", "Апполон."],
        47: ["Слова могут исцелять или ранить.", "Апполон."],
        48: ["Тот, кто ищет гармонию, должен сначала найти её в себе.", "Апполон."],
        49: ["Если доверять математике, мы бессмертны.", "Сабина Хоссенфельдер."],
        50: ["Когнитивные искажения — величайшая проблема, потому что люди верят, что они сами мыслят непредвзято.", "Сабина Хоссенфельдер."],
        51: ["Науку двигают вперёд похороны.", "Сабина Хоссенфельдер."],
        52: ["Истинная задача жизни — это искусство.", "Фридрих Ницше."],
        53: ["На небесах все интересные люди отсутствуют.", "Фридрих Ницше."],
        54: ["То, что меня не убивает, делает меня сильнее.", "Фридрих Ницше."],
        55: ["Мир — это иллюзия, созданная тайным сговором наших чувств.", "Роджер Пенроуз"],
        56: ["Звезды не предсказывают будущее — они лишь подсвечивают пути.", "Веттий Валент"],
        57: ["Как наверху, так и внизу: движения небес находят отражение в душе.", "Герметизм"],
        58: ["Пусть звезды будут твоими ориентирами, но не твоими границами.", "Веттий Валент"],
        59: ["Луна — зеркало наших эмоций, меняющее лицо с каждым циклом.", "Веттий Валент"],
        60: ["Тысячелетия прошли, но люди все еще ищут ответы в звездных узорах.", "Гвидо Бонацци"],
        61: ["Влияние планет — это язык Вселенной, который нужно научиться слышать.", "Гвидо Бонацци"],
        62: ["Судьба не высечена в камне, но звезды могут подсказать, где лежат дороги.", "Гвидо Бонацци"],
        63: ["Гороскоп — это не предсказание, а возможность понять себя глубже.", "Уильям Лилли"],
        64: ["Мы родились под звездами, но сами создаем свой свет.", "Неизвестный автор"],
        65: ["Восходящий знак — это маска, которую мы надеваем перед миром.", "Уильям Лилли"],
        66: ["Каждая планета ведет свой танец, определяя ритм нашей жизни.", "Уильям Лилли"],
        67: ["Луна учит нас, что эмоции приходят и уходят, как приливы.", "Уильям Лилли"],
        68: ["Ретроградный Меркурий не приносит хаос — он просто напоминает о незавершенных делах.", "Неизвестный автор"],
        69: ["Астрология — это искусство чтения времени, запечатленного в звездах.", "Жан-Батист Морен"],
        70: ["Каждый знак — это история, рассказанная светом и тенью.", "Жан-Батист Морен"],
        71: ["Овен прокладывает путь, Весы ищут баланс, Рыбы плывут сквозь мечты.", "Неизвестный автор"],
        72: ["Вселенная говорит с нами шепотом звезд — важно научиться слушать.", "Неизвестный автор"],
        73: ["Сатурн учит терпению, Венера — любви, Юпитер — вере в возможности.", "Жан-Батист Морен"],
        74: ["Звезды не дают готовых ответов, они лишь направляют нас к пониманию.", "Доротей Сидонский"],
        75: ["Люди смотрят в небо и видят свет, но астрологи — судьбу.", "Доротей Сидонский"],
        76: ["Кометы — посланники прошлого, несущие тайны давно забытых миров.", "Карл Саган"],
        77: ["Метеоры вспыхивают в небе, как воспоминания Вселенной о том, что было и что будет.", "Фирмик Матерн"],
        78: ["Новолуние — это не конец, а обещание нового начала.", "Фирмик Матерн"],
        79: ["Суперлуние напоминает нам, что даже самые далекие мечты могут стать ближе.", "Фирмик Матерн"],
        80: ["Во время полнолуния сердца открываются, а тайны становятся явными.", "Неизвестный автор"],
        81: ["В момент солнечного затмения день и ночь сливаются в единый миг.", "Клавдий Птолемей"],
        82: ["Когда падающая звезда рассекает небо, мгновение кажется вечностью.", "Абу Машар"],
        83: ["Парады планет — это танец небесных тел, гармония космоса в движении.", "Жан-Батист Морен"],
        84: ["Во время лунного затмения мы наблюдаем борьбу света и тьмы во Вселенной.", "Гвидо Бонацци"],
        85: ["Пролет кометы — это редкое напоминание о том, что чудеса происходят даже в пустоте.", "Гвидо Бонацци"],
        86: ["Восход Венеры на утреннем небе — символ любви, пробуждающейся в сердце.", "Неизвестный автор"],
        87: ["Зодиак — это карта звездного путешествия души сквозь время.", "Веттий Валент"],
        88: ["Когда наступает новолуние, звезды рассказывают истории, которых мы еще не слышали.", "Гвидо Бонацци"],
        89: ["Метеорные потоки — это дождь из древних посланий, сияющий в ночи.", "Неизвестный автор"],
        90: ["Полнолуние затрагивает скрытые глубины души, подобно приливу, несущему тайные эмоции.", "Фирмик Матерн"],
        91: ["Затмения — знаки перемен, как страницы, перелистываемые временем.", "Неизвестный автор"],
        92: ["Звезды — не просто свет, а древние хроники, написанные их лучами.", "Неизвестный автор"],
        93: ["Небесные явления — знаки, которые Вселенная оставляет для внимательных.", "Неизвестный автор"],
        94: ["Луна ведет разговор с приливами, и шепот волн — ее ответ.", "Неизвестный автор"],
        95: ["Великая комета — гость из глубин космоса, напоминание о том, что мы — часть чего-то большего.", "Неизвестный автор"],
    },
    "cz": {
        0: ["Vesmír šeptá těm, kteří jsou připraveni naslouchat.", "Copilot."],
        1: ["Blesk není jen hněv, ale ukazující prst osudu.", "Zeus."],
        2: ["Hrom je hlas bohů a dnes mluví k smrtelníkům.", "Zeus."],
        3: ["Bohové dávají znamení, ale moudří je umějí číst.", "Zeus."],
        4: ["Vláda nad světem znamená vidět dál než smrtelníci.", "Zeus."],
        5: ["Tajemství hlubin znají ti, kteří se odváží ponořit do propasti.", "Poseidon."],
        6: ["Suchá zem pod nohama byla kdysi částí oceánu.", "Poseidon."],
        7: ["Voda je tvůrčí i ničivá síla.", "Poseidon."],
        8: ["Nikdo neunikne svému osudu, ani bohové.", "Hádés."],
        9: ["Nebe skrývá více stínů než hvězd.", "Hádés."],
        10: ["Vzpomínka živých uchovává duše.", "Hádés."],
        11: ["Život je smlouva s osudem, která se časem rozpadne.", "Hádés."],
        12: ["Osud se klaní moudrosti, ne zuřivosti.", "Athéna."],
        13: ["Vědění je jediná síla, kterou nelze odebrat.", "Athéna."],
        14: ["Chaos ničí sám sebe, řád vytváří věčnost.", "Athéna."],
        15: ["Nehledej slávu v bitvě, pokud nejsi připraven nést její břemeno.", "Athéna."],
        16: ["Svoboda patří těm, kdo se nebojí samoty.", "Artemis."],
        17: ["Měsíc skrývá a odhaluje pravdu.", "Artemis."],
        18: ["Kdo se bojí krve, už prohrál.", "Arés."],
        19: ["Není míru bez války, není vítězství bez bolesti.", "Arés."],
        20: ["V bitvě není spravedlnost, pouze výsledek.", "Arés."],
        21: ["Meč neklade otázky, pouze odpovídá.", "Arés."],
        22: ["Země je štědrá k těm, kdo umějí čekat.", "Démétér."],
        23: ["Neztrácej spojení se svými kořeny – živí tě silou předků.", "Démétér."],
        24: ["Osud je jako úroda: co zaseješ, to sklidíš.", "Démétér."],
        25: ["Život plyne jako řeka a vše se vrací na začátek.", "Démétér."],
        26: ["Konec války viděli jen mrtví.", "Platón."],
        27: ["Osud přeje připraveným.", "Platón."],
        28: ["Myšlení je jazyk, kterým duše hovoří sama k sobě.", "Platón."],
        29: ["Nejvyšší moudrost je rozlišit dobro a zlo.", "Sókratés."],
        30: ["Život bez zkoušek není život.", "Sókratés."],
        31: ["Moudrost je vědět, jak málo víme.", "Sókratés."],
        32: ["Kdo chce pohnout světem, ať nejprve pohně sebou.", "Sókratés."],
        33: ["Přátelství je jedna duše žijící ve dvou tělech.", "Aristotelés."],
        34: ["Poznání začíná údivem.", "Aristotelés."],
        35: ["Jen ten, kdo poznal oheň, zná jeho skutečnou cenu.", "Héfaistos."],
        36: ["Řemeslo není dar, ale zkouška ducha.", "Héfaistos."],
        37: ["Svět se nestaví slovy, ale údery kladiva.", "Héfaistos."],
        38: ["Domov není místo, ale stav duše.", "Hestia."],
        39: ["Teplo nepotřebuje sílu, jen péči.", "Hestia."],
        40: ["Bez ohně není života, bez domova není štěstí.", "Hestia."],
        41: ["Rodina není pouto krve, ale pouto věrnosti.", "Héra."],
        42: ["Hněv bohyně je jako bouře.", "Héra."],
        43: ["Láska není volba, ale příkaz bohů.", "Afrodité."],
        44: ["Ten, kdo poznal lásku, spatřil božské.", "Afrodité."],
        45: ["Můžeš před láskou utíkat, ale vždy tě najde.", "Afrodité."],
        46: ["Krása není vzhled, ale odraz vnitřní harmonie.", "Apollón."],
        47: ["Slova mohou léčit i zraňovat.", "Apollón."],
        48: ["Ten, kdo hledá harmonii, musí ji nejprve najít v sobě.", "Apollón."],
        49: ["Pokud věříme matematice, jsme nesmrtelní.", "Sabine Hossenfelder."],
        50: ["Kognitivní zkreslení jsou největší problém, protože lidé věří, že myslí nezaujatě.", "Sabine Hossenfelder."],
        51: ["Věda postupuje vpřed pohřby.", "Sabine Hossenfelder."],
        52: ["Skutečným účelem života je umění.", "Friedrich Nietzsche."],
        53: ["V nebi chybí všichni zajímaví lidé.", "Friedrich Nietzsche."],
        54: ["Co mě nezabije, to mě posílí.", "Friedrich Nietzsche."],
        55: ["Svět je iluze vytvořená tajným spiknutím našich smyslů.", "Roger Penrose."],
        56: ["Hvězdy nepředpovídají budoucnost – pouze osvětlují cesty.", "Vettius Valens."],
        57: ["Jak nahoře, tak dole: pohyby nebes se odrážejí v duši.", "Hermetismus."],
        58: ["Nechť jsou hvězdy tvými průvodci, ale ne tvými hranicemi.", "Vettius Valens."],
        59: ["Měsíc je zrcadlo našich emocí, měnící tvář s každým cyklem.", "Vettius Valens."],
        60: ["Uplynula tisíciletí, ale lidé stále hledají odpovědi ve hvězdných vzorech.", "Guido Bonazzi."],
        61: ["Vliv planet je jazykem Vesmíru – je třeba se mu naučit naslouchat.", "Guido Bonazzi."],
        62: ["Osud není vytesán do kamene, ale hvězdy mohou naznačit cesty vpřed.", "Guido Bonazzi."],
        63: ["Horoskop není předpověď, ale příležitost hlouběji porozumět sobě.", "William Lilly."],
        64: ["Narodili jsme se pod hvězdami, ale své světlo si vytváříme sami.", "Neznámý autor."],
        65: ["Vzestupný znamení je maska, kterou nosíme před světem.", "William Lilly."],
        66: ["Každá planeta tančí svůj tanec a určuje rytmus našich životů.", "William Lilly."],
        67: ["Měsíc nás učí, že emoce přicházejí a odcházejí jako příliv a odliv.", "William Lilly."],
        68: ["Retrográdní Merkur nepřináší chaos – připomíná nám nedokončené záležitosti.", "Neznámý autor."],
        69: ["Astrologie je umění číst čas, vepsaný do hvězd.", "Jean-Baptiste Morin."],
        70: ["Každé znamení zvěrokruhu je příběh vyprávěný světlem a stínem.", "Jean-Baptiste Morin."],
        71: ["Beran razí cestu, Váhy hledají rovnováhu, Ryby plují skrze sny.", "Neznámý autor."],
        72: ["Vesmír k nám promlouvá šepotem hvězd – je důležité se naučit naslouchat.", "Neznámý autor."],
        73: ["Saturn učí trpělivosti, Venuše lásce, Jupiter víře v možnosti.", "Jean-Baptiste Morin."],
        74: ["Hvězdy nedávají hotové odpovědi, pouze nás vedou k porozumění.", "Dorotheos z Sidonu."],
        75: ["Lidé hledí na nebe a vidí světlo, ale astrologové vidí osud.", "Dorotheos z Sidonu."],
        76: ["Komety jsou poslové z minulosti, nesoucí tajemství dávno zapomenutých světů.", "Carl Sagan."],
        77: ["Meteory září na obloze jako vzpomínky Vesmíru na to, co bylo a co bude.", "Firmicus Maternus."],
        78: ["Novoluní není konec, ale slib nového začátku.", "Firmicus Maternus."],
        79: ["Superúplněk nám připomíná, že i ty nejvzdálenější sny se mohou přiblížit.", "Firmicus Maternus."],
        80: ["Za úplňku se otevírají srdce a tajemství vycházejí najevo.", "Neznámý autor."],
        81: ["Při zatmění Slunce se den a noc spojí v jediný okamžik.", "Klaudios Ptolemaios."],
        82: ["Když padající hvězda protne oblohu, okamžik se zdá být věčností.", "Abú Mašar."],
        83: ["Planetární konjunkce je tanec nebeských těles, harmonie vesmíru v pohybu.", "Jean-Baptiste Morin."],
        84: ["Při zatmění Měsíce pozorujeme zápas světla a tmy ve Vesmíru.", "Guido Bonazzi."],
        85: ["Průlet komety je vzácná připomínka, že zázraky existují i v prázdnotě.", "Guido Bonazzi."],
        86: ["Venuše na ranní obloze je symbolem lásky probouzející se v srdci.", "Neznámý autor."],
        87: ["Zvěrokruh je mapa hvězdné cesty duše časem.", "Vettius Valens."],
        88: ["Když nastane novoluní, hvězdy vyprávějí příběhy, které jsme ještě neslyšeli.", "Guido Bonazzi."],
        89: ["Meteorické roje jsou déšť prastarých poselství zářících v noci.", "Neznámý autor."],
        90: ["Úplněk zasahuje skryté hlubiny duše, jako příliv nesoucí tajné emoce.", "Firmicus Maternus."],
        91: ["Zatmění jsou znamení změn, jako stránky otáčené časem.", "Neznámý autor."],
        92: ["Hvězdy nejsou jen světlo, ale staré kroniky psané jejich paprsky.", "Neznámý autor."],
        93: ["Nebeské úkazy jsou znamení, která Vesmír zanechává pozorným.", "Neznámý autor."],
        94: ["Měsíc vede rozhovor s přílivem a šepot vln je jeho odpověď.", "Neznámý autor."],
        95: ["Velká kometa je host z hlubin vesmíru, připomínka, že jsme částí něčeho většího.", "Neznámý autor."],
    }
   
}

export default quotes;