const quotes = {
    "ru": {
        1: "Все, что человеческий разум способен понять и во что он способен поверить, достижимо. — Наполеон Хилл.",
        2: "Сложнее всего начать действовать, все остальное зависит только от упорства. — Амелия Эрхарт.",
        3: "Начинать всегда стоит с того, что сеет сомнения. — Борис Стругацкий.",
        4: "Возможности не приходят сами — вы создаете их. — Крис Гроссер.",
        5: "Неудача — это возможность начать заново, но уже более мудро. — Генри Форд.",
        6: "Всегда смотрите на солнце — и тени будут позади вас. — Уолт Уитмен.",
        7: "Если я полон решимости, я преодолею любое препятствие. — Абай Кунанбаев.",
        8: "Обстоятельства часто можно изменить, изменив свое отношение к ним. — Элеонора Рузвельт.",
        9: "Вдохновение приходит только во время работы. — Габриэль Гарсиа Маркес.",
        10: "Самый важный шаг — всегда следующий. — Брайан Трейси.",
        11: "Все, что раздражает в других, может вести к пониманию себя. — Карл Густав Юнг.",
        12: "Если проблему можно решить, не стоит о ней беспокоиться. — Далай-лама XIV.",
        13: "Счастье — это не нечто готовое. Счастье зависит только от ваших действий. — Далай-лама XIV.",
        14: "Сила не зависит от физических возможностей. Ее источник — неукротимая воля. — Махатма Ганди.",
        15: "Постановка целей — это первый шаг к превращению невидимого в видимое. — Тони Роббинс.",
        16: "Если что-то вообще стоит пробовать, это стоит попробовать не меньше 10 раз. — Артур Гордон Линклеттер.",
        17: "Если вам не нравится дорога, по которой вы идете, начните прокладывать другую. — Долли Партон.",
        18: "Дойдя до конца, люди смеются над страхами, мучившими их вначале. — Пауло Коэльо.",
        19: "Я твердо верю в удачу. И я заметил: чем больше я работаю, тем больше она мне улыбается. — Томас Джефферсон.",
        20: "Искусство быть мудрым — это искусство знать, чем можно пренебречь. — Уильям Джеймс.",
        21: "Постарайтесь получить то, что любите, иначе придется полюбить то, что получили. — Джордж Бернард Шоу.",
        22: "Не расставайтесь со своими иллюзиями. Когда их не станет, может быть, вы и продолжите существовать, но перестанете жить. — Марк Твен.",
        23: "Если вы не знаете, куда идете, любая дорога приведет вас туда. — Джордж Харрисон.",
        24: "Только те, кто рискуют зайти слишком далеко, способны выяснить, как далеко они могут зайти. — Томас Стернз Элиот.",
        25: "Мотивация — это огонь изнутри. Если кто-то попытается зажечь этот огонь под вами, скорее всего, он очень быстро сгорит. — Стивен Кови.",
        26: "Живите в соответствии со своим воображением, а не своим прошлым. — Стивен Кови.",
        27: "Мечтайте по-крупному и осмельтесь потерпеть неудачу. — Норман Воган.",
        28: "Дайте человеку цель, ради которой стоит жить, и он сможет выжить в любой ситуации. — Иоганн Вольфганг Гёте.",
        29: "Лидеры не рождаются и не делаются кем-либо — они делают себя сами. — Стивен Кови.",
        30: "Через 20 лет вы будете больше разочарованы теми вещами, которые вы не делали, чем теми, которые вы сделали. Так отчальте от тихой пристани. Почувствуйте попутный ветер в вашем парусе. Двигайтесь вперед, действуйте, открывайте! — Г. Джексон Браун.",
        31: "Делайте, что можете, с тем, что имеете, там, где вы есть. — Теодор Рузвельт.",
        32: "Не ждите; тот самый момент не наступает никогда. — Наполеон Хилл.",
        33: "Если вы хотите изменить мир, начните с себя. — Махатма Ганди.",
        34: "Не позволяйте вчерашнему дню занимать слишком много места в сегодняшнем. — Уилл Роджерс.",
        35: "Измените свою жизнь сегодня. Не рассчитывайте на будущее, действуйте сейчас, не откладывая. — Симона де Бовуар.",
        36: "Единственным пределом наших завтрашних свершений станут наши сегодняшние сомнения. — Франклин Д. Рузвельт.",
        37: "Делай сегодня то, что другие не хотят — завтра будешь жить так, как другие не могут. — Джаред Лето.",
        38: "Кто-то отдыхает сегодня в тени, потому что кто-то посадил дерево много лет назад. — Уоррен Баффетт.",
        39: "Никто не может вернуться назад и начать все сначала, но любой человек может начать сегодня и создать новое окончание. — Сэмюэл Джонсон.",
        40: "Мужество — это сопротивление страху, а не его отсутствие. — Марк Твен.",
        41: "Храбрость не всегда кричит. Иногда храбрость говорит тихим голосом в конце дня: Завтра я попытаюсь еще раз. — Мэри Энн Редмачер.",
        42: "Если вы хотите иметь то, что никогда не имели, вам придется делать то, что никогда не делали. — Коко Шанель.",
        43: "Каждую ночь, прежде чем уснуть, представляйте себе свой идеальный завтрашний день. Вы увидите, во многом так и будет. — Брайан Трейси.",
        44: "Каждый день не может быть хорошим, но есть что-то хорошее в каждом дне. — Элис Морз Эрл.",
        45: "Большинство людей упускают свои возможности, потому что она бывает одета в комбинезон и с виду напоминает работу. — Томас Эдисон.",
        46: "Вы хотите знать, кто вы? Не спрашивайте. Действуйте! Действие будет описывать и определять вас. — Томас Джефферсон.",
        47: "Вы должны делать то, что, как вам кажется, вы не в состоянии сделать. — Элеонора Рузвельт.",
        48: "Даже если вы находитесь на правильном пути, вас собьют, если вы просто сидите там. — Уилл Роджерс.",
        49: "Постановка целей является первым шагом на пути превращения мечты в реальность. — Энтони Роббинс.",
        50: "Настоящее открытие — не в поиске новых земель, а в новом взгляде. — Марсель Пруст.",
        51: "В конце концов, мы можем вынести гораздо больше, чем мы думаем. — Фрида Кало.",
        52: "Действия не всегда приносят счастье, но не бывает счастья без действия. — Бенджамин Дизраэли.",
        53: "Если Вы работаете над поставленными целями, то эти цели будут работать на вас. — Джим Рон.",
        54: "Когда необходимо сделать выбор, а вы его не делаете, — это тоже выбор. — Уильям Джеймс.",
        55: "Мы должны использовать время мудро и помнить: правое дело можно начать в любую минуту. — Нельсон Мандела.",
        56: "Стремитесь не к успеху, а к ценностям, которые он дает. — Альберт Эйнштейн.",
        57: "Логика может привести вас от пункта А к пункту Б, а воображение — куда угодно. — Альберт Эйнштейн.",
        58: "Ваше время ограничено, не тратьте его, живя чужой жизнью. — Стив Джобс.",
        59: "Неважно, как медленно вы идете, до тех пор, пока вы не остановитесь. — Конфуций.",
        60: "Путь в тысячу ли начинается с первого шага. — Лао-цзы.",
        61: "Трудности укрепляют ум, как труд укрепляет тело. — Сенека.",
        62: "Вы не можете менять направление ветра, но всегда можете поднять паруса, чтобы достичь своей цели. — Оскар Уайльд.",
        63: "Верный способ начать что-то — бросить говорить и делать. — Уолт Дисней.",
        64: "Пройденный путь и есть награда. — Стив Джобс.",
        65: "Свобода ничего не стоит, если она не включает в себя свободу ошибаться. — Махатма Ганди.",
        66: "Умение жить — самая редкая вещь в мире. Большинство людей просто существует. — Оскар Уайльд.",
        67: "То, что мы любим, говорит нам о том, кто мы есть. — Фома Аквинский.",
        68: "Когда вам покажется, что цель недостижима, не изменяйте цель — изменяйте свой план действий. — Конфуций.",
        69: "Будьте собой. Все остальные роли уже заняты. — Оскар Уайльд.",
        70: "Лучше работать без определенной цели, чем ничего не делать. — Сократ.",
        71: "Просыпаясь утром, спроси себя: Что я должен сделать? Вечером, прежде чем заснуть: Что я сделал? — Пифагор.",
        72: "Помните, что даже самый тяжелый час в вашей жизни — всего 60 минут. — Софокл.",
        73: "Хорошее время не с неба падает, а мы его делаем, оно заключается в сердце нашем. — Федор Достоевский.",
        74: "Секрет перемен состоит в том, чтобы сосредоточить на создании нового, а не на борьбе со старым. — Сократ.",
        75: "Наука — это организованное знание. Мудрость — это организованная жизнь. — Иммануил Кант.",
        76: "Выживает не самый сильный из видов и не самый умный, а тот, кто лучше других реагирует на изменения. — Чарльз Дарвин.",
        77: "Человек всю жизнь не живет, а сочиняет себя, самосочиняется. — Фёдор Достоевский.",
        78: "Будь честен с самим собой, и с людьми, всегда делай все вовремя, никогда не сдавайся, иди к своим целям, даже если все плохо. — Стив Джобс.",
        79: "Существует только один путь к счастью — перестать беспокоиться о вещах, которые не подвластны нашей воле. — Эпиктет.",
        80: "Большинство людей в действительности не хотят свободы, потому что она предполагает ответственность, а ответственность большинство людей страшит. — Зигмунд Фрейд.",
        81: "Действие даже самого крохотного существа приводит к изменениям во всей вселенной. — Никола Тесла.",
        82: "Победа — это еще не все, все — это постоянное желание побеждать. — Винс Ломбарди.",
        83: "Не будучи в силах свершить великое, свершай малое великим способом. — Наполеон Хилл.",
        84: "Предрассудки — это бремя, которое путает прошлое, ставит под угрозу будущее и делает настоящее недоступными. — Майя Анжелу.",
        85: "Грамм собственного опыта стоит дороже тонны чужих наставлений. — Махатма Ганди.",
        86: "Не стоит быть тенью в чужом фонаре, когда можно сиять своим собственным светом. — Алексей Христинин.",
        87: "Вы не сможете пересечь море, просто стоя и вглядываясь в воду. Не тратьте время на напрасные желания. — Рабиндранат Тагор.",
        88: "Обязательно дружите с теми, кто лучше вас. Будете мучиться, но расти. — Вера Полозкова.",
        89: "Планы — это только набор намерений. Если они тут же не перерастают в конкретные действия, направленные на достижение ваших целей. Но важно помнить, что каждая минута, потраченная на планирование, будет потом экономить огромное количество времени и денег. — Дмитрий Брейтенбихер.",
        90: "Тот, кто не может изменить свое мышление, не может изменить ничего. — Джордж Бернард Шоу.",
        91: "Не бойтесь отказываться от хорошего в пользу отличного. — Джон Рокфеллер.",
        92: "Мы должны использовать время, как инструмент, а не как диван. — Джон Фицджеральд Кеннеди.",
        93: "Мы свободны выбирать наши действия, но мы не можем выбирать последствия этих действий. — Стивен Кови.",
        94: "Лучше потерпеть неудачу в оригинальности, чем преуспеть в подражании. — Герман Мелвилл.",
        95: "Мы можем столкнуться с множеством поражений, но не должны быть побежденными. — Майя Анжелу.",
        96: "Большую работу поручают тому, кто показывает способность перерасти маленькую. — Теодор Рузвельт.",
        97: "Вы никогда не будете слишком стары, чтобы ставить другую цель или мечтать о новой мечте. — Клайв Стейплз Льюис.",
        98: "Не отступай перед трудностями. Смотри им прямо в лицо. Смотри, пока не одолеешь их. — Чарльз Диккенс.",
        99: "Чем больше трудностей мы преодолеваем, тем легче принимаем свое будущее. — Майкл Хайятт.",
        100: "Не бойтесь совершенства. Вы его никогда не достигнете. — Сальвадор Дали.",
        101: "Не слушайте тех, кто велит играть на скрипке, когда вы отлично играете на барабанах. — Жозе Моуринью.",
        102: "Нельзя открыть новую землю, не согласившись сначала и надолго потерять из виду любой берег. — Андре Жид.",
        103: "Вы не должны быть великими, чтобы начать, но вы должны начать, чтобы быть великими. — Зиг Зиглар.",
        104: "Все то, что лежит позади нас и что лежит перед нами, — мелочи по сравнению с тем, что лежит внутри нас. — Ральф Уолдо Эмерсон.",
        105: "Только через осуществление великих целей человек обнаруживает в себе великий характер, делающий его маяком для других. — Георг Гегель.",
        106: "Величайшая польза, которую можно извлечь из жизни, — потратить жизнь на дело, которое переживёт нас. — Уильям Джеймс.",
        107: "Когда человеку кажется, что всё идёт наперекосяк, в его жизнь пытается войти нечто чудесное. — Далай-лама XIV.",
        108: "Вы не можете пройти ни одного дня, не оказав влияния на мир вокруг вас. То, что вы делаете, имеет значение, и вы должны решить, какую значимость будут иметь ваши действия. — Джейн Гудолл.",
        109: "Вы должны верить в себя даже тогда, когда в вас сомневается весь мир. — Шри Чинмой.",
        110: "Отдавай миру лучшее, что у тебя есть, и лучшее устремится обратно к тебе. — Шри Чинмой.",
        111: "Музыка — это стенография чувств. — Лев Толстой.",
        112: "Жизнь — это 10 процентов того, что с вами происходит, и 90 процентов того, как вы на это реагируете. — Лу Хольц.",
        113: "Только я могу изменить свою жизнь. Никто не может сделать это за меня. — Кэрол Бернетт.",
        114: "Смысл жизни не в том, чтобы ждать, когда закончится гроза, а в том, чтобы учиться танцевать под дождем. — Вивиан Грин.",
        115: "Мы находим в жизни только то, что сами вкладываем в нее. — Ральф Уолдо Эмерсон.",
        116: "То, что вы делаете, имеет смысл, и вы должны решить, каким смыслом наполнить жизнь. — Джейн Гудолл.",
        117: "Жизнь — это путешествие, а не пункт назначения. — Ральф Уолдо Эмерсон.",
        118: "Жизнь состоит не в том, чтобы найти себя. Жизнь состоит в том, чтобы создать себя. — Джордж Бернард Шоу.",
        119: "Ни разу не упасть — не самая большая заслуга в жизни. Главное — каждый раз подниматься. — Нельсон Мандела.",
        120: "Творчество требует мужества. — Анри Матисс.",
        121: "Не пытайтесь остановить то, что неизбежно. В конце концов, всё в жизни становится на свои места, потому что всё циклично. — Иван Пьянов.",
        122: "Лучшие и прекраснейшие вещи в мире нельзя увидеть, к ним нельзя даже прикоснуться. Их надо чувствовать сердцем. — Хелен Адамс Келлер.",
        123: "Вчера я был умным, хотел изменить мир. Сегодня я мудрый, и поэтому меняю себя. — Шри Чинмой.",
        124: "Победы не делают вас сильнее. Сила формируется в борьбе. Когда, преодолевая трудности, вы решаете не сдаваться — тогда вы проявляете силу. — Арнольд Шварценеггер.",
        125: "Каждый человек на земле, чем бы он ни занимался, играет главную роль в истории мира. И обычно даже не знает об этом. — Пауло Коэльо.",
        126: "Никогда не опускайте голову. Держите её высоко. Смотрите миру прямо в глаза. — Хелен Адамс Келлер.",
        127: "Страх побеждает больше людей, чем любая другая вещь в мире. — Ральф Уолдо Эмерсон.",
        128: "За свою карьеру я пропустил более 9000 бросков, проиграл почти 300 игр. 26 раз мне доверяли сделать финальный победный бросок, и я промахивался. Я терпел поражения снова, и снова, и снова. И именно поэтому я добился успеха. — Майкл Джордан.",
        129: "Успех — это умение двигаться от неудачи к неудаче, не теряя энтузиазма. — Уинстон Черчилль.",
        130: "Успех не является ключом к счастью. Счастье же — самый важный ключ к успеху. Если Вам нравится то, чем Вы занимаетесь — Вы обязательно добьетесь успеха. — Альберт Швейцер.",
        131: "Многие из тех, кто терпит неудачу в жизни, — это люди, которые не осознавали, насколько они были близки к успеху, когда они сдались. — Томас Эдисон.",
        132: "Успех не состоит в том, чтобы никогда не совершать грубых ошибок, но никогда не повторять одно и то же во второй раз. — Джордж Бернард Шоу.",
        133: "Успех — это сумма мелких усилий, повторяющихся день за днем. — Роберт Кольер.",
        134: "Успех не приходит к вам. Это вы идете к нему. — Марва Коллинз.",
        135: "Единственная истинная мудрость — знать, что ты ничего не знаешь. — Сократ.",
        136: "Образование поможет выжить. Самообразование приведет вас к успеху. — Джим Рон.",
        137: "Успех обычно приходит к тем, кто слишком занят, чтобы искать его. — Генри Дэвид Торо.",
        138: "Единственное место, где успех предшествует работе, — это словарь. — Винс Ломбарди.",
        139: "Успех — это лестница, на которую не взобраться, держа руки в карманах. — Зиг Зиглар.",
        140: "Я понял, что успех должен измеряться не столько положением, которого человек достиг в своей жизни, сколько теми препятствиями, которые ему пришлось преодолеть на пути к успеху. — Букер Тальяферро Вашингтон.",
        141: "В жизни нет большего удовольствия, чем удовольствие от преодоления трудностей на пути к успеху. — Сэмюэл Джонсон.",
        142: "Для того, чтобы преуспеть, мы первым делом должны верить, что мы можем. — Никос Казантзакис.",
        143: "Пределы возможного — лишь иллюзия. — Карлос Кастанеда.",
        144: "Когда одна дверь счастья закрывается, открывается другая; но мы часто не замечаем ее, уставившись взглядом в закрытую дверь. — Хелен Адамс Келлер.",
        145: "Цели — это топливо в печи достижений. — Брайан Трейси.",
        146: "То, что вы получаете, достигая своих целей, не так важно, как то, кем вы становитесь. — Зиг Зиглар.",
        147: "Дисциплина — это решение делать то, чего очень не хочется делать, чтобы достичь того, чего очень хочется. — Джон Максвелл.",
        148: "Берегите свои видения и мечты, поскольку они — детища вашей души, чертежи ваших высших достижений. — Наполеон Хилл.",
        149: "Чем лучше вы себя чувствуете, тем выше самооценка, а чем выше ваша самооценка, тем выше ваши цели и тем большего вы сможете достичь в жизни. — Брайан Трейси.",
        150: "Оставаться собой в мире, который постоянно пытается сделать вас чем-нибудь другим, — величайшее достижение. — Ральф Уолдо Эмерсон.",
        151: "Сложные времена создают сильных людей. Сильные люди создают хорошие времена. — Г. Майкл Хопф.",
        152: "Сомнение — начало мудрости. — Аристотель.",
        153: "Ты становишься тем, во что веришь. — Опра Уинфри.",
        154: "Слова имеют силу изменять восприятие реальности. — Тони Роббинс.",
        155: "Лучший способ предсказать будущее — создать его. — Абрахам Линкольн.",
        156: "Неудача — это приправа, придающая успеху его вкус. — Трумен Капоте.",
        157: "Идеи — это капиталы, которые не гибнут. — Карл Маркс.",
        158: "Вдохновение существует, но оно должно застать тебя за работой. — Пабло Пикассо.",
        159: "Секрет гения — это работа, настойчивость и здравый смысл. — Томас Эдисон.",
        160: "Самый опасный яд — это чувство безнаказанности. — Федор Достоевский.",
        161: "Цель искусства — очищать душу от повседневности. — Казимир Малевич.",
        162: "В каждом человеке солнце. Только дайте ему светить. — Сократ.",
        163: "Страсть — это энергия, которая ощущает силу. — Билл Гейтс.",
        164: "Разум, однажды расширивший свои границы, никогда не вернется в прежние. — Альберт Эйнштейн.",
        165: "Доверие — это роскошь, которую нужно заслужить. — Сергей Брин.",
        166: "Смех — это солнце, прогоняющее зиму с человеческого лица. — Виктор Гюго.",
        167: "Настоящая власть — это умение превращать желания в реальность. — Джордж Мартин.",
        168: "Молчание — последний крик души. — Фридрих Ницше.",
        169: "Победа над страхом — это начало мудрости. — Бертран Рассел.",
        170: "Креативность требует смелости отпустить уверенность. — Эрих Фромм.",
        171: "Счастье зависит от нас самих. — Аристотель",
        172: "Единственная истинная мудрость заключается в осознании того, что ты ничего не знаешь. — Сократ",
        173: "Непроверенная жизнь не стоит того, чтобы жить. — Сократ",
        174: "Мы — то, что мы делаем регулярно. Значит, совершенство — это не действие, а привычка. — Аристотель",
        175: "Человек — мера всех вещей. — Протагор",
        176: "Благополучие достигается шаг за шагом, и, тем не менее, само по себе оно не является маленьким достижением. — Зенон из Кития",
        177: "Смерть нас не касается, потому что, пока мы существуем, смерти нет. Когда же она приходит, нас уже нет. — Эпикур",
        178: "У него больше всего, кто более всего доволен самым малым. — Диоген",
        179: "Учиться — это не только получать информацию, но и трансформировать себя. — Платон",
        180: "Свобода — это способность действовать или не действовать, чтобы стремиться к добру или избегать зла. — Эпиктет",
        181: "Важно не то, что с вами происходит, а как вы на это реагируете. — Эпиктет",
        182: "Справедливость означает заниматься своими делами и не вмешиваться в дела других людей. — Платон",
        183: "Тот, кто не умеет быть хорошим слугой, не станет хорошим господином. — Аристотель",          
    },
    "eng": {
        1: "Whatever the mind of man can conceive and believe, it can achieve. — Napoleon Hill",
        2: "The most difficult thing is the decision to act, the rest is merely tenacity. — Amelia Earhart",
        3: "You should always start with what seeds doubt. — Boris Strugatsky",
        4: "Opportunities don’t happen. You create them. — Chris Grosser",
        5: "Failure is simply the opportunity to begin again, this time more intelligently. — Henry Ford",
        6: "Keep your face always toward the sunshine—and shadows will fall behind you. — Walt Whitman",
        7: "If I am determined, I will overcome any obstacle. — Abai Kunanbayev",
        8: "You can often change your circumstances by changing your attitude. — Eleanor Roosevelt",
        9: "Inspiration comes only during work. — Gabriel García Márquez",
        10: "The most important step is always the next one. — Brian Tracy",
        11: "Everything that irritates us about others can lead us to an understanding of ourselves. — Carl Gustav Jung",
        12: "If a problem is fixable, there’s no need to worry about it. — Dalai Lama XIV",
        13: "Happiness is not something ready made. It comes from your own actions. — Dalai Lama XIV",
        14: "Strength does not come from physical capacity. It comes from an indomitable will. — Mahatma Gandhi",
        15: "Setting goals is the first step in turning the invisible into the visible. — Tony Robbins",
        16: "Anything worth doing is worth doing at least ten times. — Art Linkletter",
        17: "If you don't like the road you're walking, start paving another one. — Dolly Parton",
        18: "By the end, people laugh at the fears that tortured them at the beginning. — Paulo Coelho",
        19: "I am a great believer in luck, and I find the harder I work, the more I have of it. — Thomas Jefferson",
        20: "The art of being wise is the art of knowing what to overlook. — William James",
        21: "Try to get what you love, or you will have to love what you get. — George Bernard Shaw",
        22: "Don’t part with your illusions. When they are gone, you may still exist, but you have ceased to live. — Mark Twain",
        23: "If you don't know where you're going, any road will take you there. — George Harrison",
        24: "Only those who will risk going too far can possibly find out how far one can go. — T.S. Eliot",
        25: "Motivation is a fire from within. If someone else tries to light that fire under you, chances are it will burn very briefly. — Stephen Covey",
        26: "Live out of your imagination, not your history. — Stephen Covey",
        27: "Dream big and dare to fail. — Norman Vaughan",
        28: "Give a person a purpose to live for, and they can survive any situation. — Johann Wolfgang von Goethe",
        29: "Leaders are not born or made—they make themselves. — Stephen Covey",
        30: "Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do. So throw off the bowlines, sail away from the safe harbor, catch the trade winds in your sails. Explore. Dream. Discover. — H. Jackson Brown Jr.",
        31: "Do what you can, with what you have, where you are. — Theodore Roosevelt",
        32: "Don’t wait; the time will never be just right. — Napoleon Hill",
        33: "If you want to change the world, start with yourself. — Mahatma Gandhi",
        34: "Don’t let yesterday take up too much of today. — Will Rogers",
        35: "Change your life today. Don't rely on the future, act now, without delay. — Simone de Beauvoir",
        36: "The only thing we have to fear about tomorrow's achievements are today's doubts. — Franklin D. Roosevelt",
        37: "Do today what others won't, so tomorrow you can live like others can't. — Jared Leto",
        38: "Someone's resting in the shade today because someone planted a tree long ago. — Warren Buffett",
        39: "No one can go back and start new, but anyone can start today and create a new ending. — Samuel Johnson",
        40: "Courage is resistance to fear, not its absence. — Mark Twain",
        41: "Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying: I will try again tomorrow. — Mary Anne Radmacher",
        42: "If you want something you’ve never had, you’ll have to do something you’ve never done. — Coco Chanel",
        43: "Every night before bed, envision your ideal tomorrow. You'll find, to a great extent, it will come true. — Brian Tracy",
        44: "Every day can't be good, but there is something good in every day. — Alice Morse Earle",
        45: "Most people miss opportunity because it is dressed in overalls and looks like work. — Thomas Edison",
        46: "Do you want to know who you are? Don’t ask. Act! Action will delineate and define you. — Thomas Jefferson",
        47: "You must do the thing you think you cannot do. — Eleanor Roosevelt",
        48: "Even if you are on the right track, you will get run over if you just sit there. — Will Rogers",
        49: "Setting goals is the first step in turning dreams into reality. — Tony Robbins",
        50: "The real voyage of discovery consists not in seeking new landscapes, but in having new eyes. — Marcel Proust",
        51: "At the end of the day, we can endure much more than we think we can. — Frida Kahlo",
        52: "Action may not always bring happiness, but there is no happiness without action. — Benjamin Disraeli",
        53: "If you work on your goals, your goals will work on you. — Jim Rohn",
        54: "When you have to make a choice and you don’t make it, that is in itself a choice. — William James",
        55: "We must use time wisely and forever realize that the time is always ripe to do right. — Nelson Mandela",
        56: "Strive not to be a success, but rather to be of value. — Albert Einstein",
        57: "Logic will get you from A to B. Imagination will take you everywhere. — Albert Einstein",
        58: "Your time is limited, don’t waste it living someone else’s life. — Steve Jobs",
        59: "It does not matter how slowly you go as long as you do not stop. — Confucius",
        60: "The journey of a thousand miles begins with a single step. — Lao Tzu",
        61: "Difficulties strengthen the mind, as labor strengthens the body. — Seneca",
        62: "You can't change the direction of the wind, but you can adjust your sails to reach your destination. — Oscar Wilde",
        63: "The way to get started is to quit talking and begin doing. — Walt Disney",
        64: "The journey is the reward. — Steve Jobs",
        65: "Freedom is not worth having if it does not include the freedom to make mistakes. — Mahatma Gandhi",
        66: "To live is the rarest thing in the world. Most people exist, that is all. — Oscar Wilde",
        67: "What we love tells us what we are. — Thomas Aquinas",
        68: "When it becomes obvious that the goals cannot be reached, don't adjust the goals, adjust the action steps. — Confucius",
        69: "Be yourself. Everyone else is already taken. — Oscar Wilde",
        70: "It is better to act without a clear purpose than to do nothing. — Socrates",
        71: "When you wake up in the morning, ask yourself: What am I to do? Before sleeping at night: What have I done? — Pythagoras",
        72: "Remember, even the hardest hour of your life is just 60 minutes. — Sophocles",
        73: "Good times don’t fall from the sky; we create them, and they live in our hearts. — Fyodor Dostoevsky",
        74: "The secret of change is to focus all your energy not on fighting the old but on building the new. — Socrates",
        75: "Science is organized knowledge. Wisdom is organized life. — Immanuel Kant",
        76: "It is not the strongest of the species that survives, nor the most intelligent, but the one most responsive to change. — Charles Darwin",
        77: "Man does not simply live his life; he creates and recreates himself. — Fyodor Dostoevsky",
        78: "Be honest with yourself and with people, always do things on time, never give up, and pursue your goals even when things are tough. — Steve Jobs",
        79: "There is only one way to happiness: stop worrying about things beyond our control. — Epictetus",
        80: "Most people do not really want freedom, because freedom involves responsibility, and most people are frightened of responsibility. — Sigmund Freud",
        81: "The actions of even the smallest creature can lead to changes across the universe. — Nikola Tesla",
        82: "Victory is not everything; everything is the constant desire to win. — Vince Lombardi",
        83: "If you cannot do great things, do small things in a great way. — Napoleon Hill",
        84: "Prejudices are burdens that confuse the past, threaten the future, and make the present inaccessible. — Maya Angelou",
        85: "A gram of one's own experience is worth more than a ton of someone else's advice. — Mahatma Gandhi",
        86: "Do not be a shadow in someone else's lantern when you can shine your own light. — Alexey Khristinin",
        87: "You cannot cross the sea merely by standing and staring at the water. Do not spend time on idle wishes. — Rabindranath Tagore",
        88: "Always befriend those who are better than you. It will be painful, but you will grow. — Vera Polozkova",
        89: "Plans are just a set of intentions unless they immediately turn into specific actions aimed at achieving your goals. But remember, every minute spent planning will save you a lot of time and money later. — Dmitry Breitenbicher",
        90: "Those who cannot change their thinking cannot change anything. — George Bernard Shaw",
        91: "Don't be afraid to give up the good to go for the great. — John D. Rockefeller",
        92: "We must use time as a tool, not as a couch. — John F. Kennedy",
        93: "We are free to choose our actions, but we cannot choose the consequences of those actions. — Stephen Covey",
        94: "It is better to fail in originality than to succeed in imitation. — Herman Melville",
        95: "We may encounter many defeats, but we must not be defeated. — Maya Angelou",
        96: "Big tasks are given to those who show the ability to outgrow smaller ones. — Theodore Roosevelt",
        97: "You are never too old to set another goal or to dream a new dream. — C.S. Lewis",
        98: "Do not back down before difficulties. Look them straight in the face. Look until you overcome them. — Charles Dickens",
        99: "The more difficulties we overcome, the easier it becomes to face the future. — Michael Hyatt",
        100: "Don't fear perfection. You'll never reach it. — Salvador Dalí",
        101: "Don't listen to those who tell you to play the violin when you excel at playing the drums. — José Mourinho",
        102: "Man cannot discover new oceans unless he has the courage to lose sight of the shore for a long time. — André Gide",
        103: "You don’t have to be great to start, but you have to start to be great. — Zig Ziglar",
        104: "What lies behind us and what lies before us are tiny matters compared to what lies within us. — Ralph Waldo Emerson",
        105: "Only through the pursuit of great goals does one discover a great character within, making them a beacon for others. — Georg Hegel",
        106: "The greatest use of life is to spend it on something that will outlast it. — William James",
        107: "When it seems that everything is going wrong, something wonderful is trying to enter your life. — Dalai Lama XIV",
        108: "You cannot go through a single day without having an impact on the world around you. What you do makes a difference, and you have to decide what kind of difference you want to make. — Jane Goodall",
        109: "You must believe in yourself even when the whole world doubts you. — Sri Chinmoy",
        110: "Give the world the best you have, and the best will come back to you. — Sri Chinmoy",
        111: "Music is the shorthand of emotion. — Leo Tolstoy",
        112: "Life is 10 percent what happens to you and 90 percent how you react to it. — Lou Holtz",
        113: "I can only change my life. No one can do it for me. — Carol Burnett",
        114: "Life isn’t about waiting for the storm to pass; it’s about learning to dance in the rain. — Vivian Greene",
        115: "We find in life only what we put into it. — Ralph Waldo Emerson",
        116: "What you do makes sense, and you must decide what meaning to fill life with. — Jane Goodall",
        117: "Life is a journey, not a destination. — Ralph Waldo Emerson",
        118: "Life isn’t about finding yourself. Life is about creating yourself. — George Bernard Shaw",
        119: "The greatest glory in living lies not in never falling, but in rising every time we fall. — Nelson Mandela",
        120: "Creativity takes courage. — Henri Matisse",
        121: "Do not try to stop what is inevitable. In the end, everything in life falls into place because everything is cyclical. — Ivan Pyanov",
        122: "The best and most beautiful things in the world cannot be seen or even touched. They must be felt with the heart. — Helen Keller",
        123: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself. — Sri Chinmoy",
        124: "Strength doesn’t come from victories. Strength is forged in struggles. When you overcome difficulties and decide not to give up—that’s when you demonstrate strength. — Arnold Schwarzenegger",
        125: "Every person on Earth, no matter what they do, plays a leading role in the story of the world. And they usually don’t even know it. — Paulo Coelho",
        126: "Never bend your head. Hold it high. Look the world straight in the eye. — Helen Keller",
        127: "Fear defeats more people than any other thing in the world. — Ralph Waldo Emerson",
        128: "Throughout my career, I’ve missed over 9,000 shots and lost almost 300 games. Twenty-six times, I was entrusted to make the game-winning shot, and I missed. I’ve failed over and over and over again. And that is why I succeeded. — Michael Jordan",
        129: "Success is the ability to go from failure to failure without losing your enthusiasm. — Winston Churchill",
        130: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. — Albert Schweitzer",
        131: "Many of life’s failures are people who did not realize how close they were to success when they gave up. — Thomas Edison",
        132: "Success does not consist in never making mistakes but in never making the same one a second time. — George Bernard Shaw",
        133: "Success is the sum of small efforts, repeated day in and day out. — Robert Collier",
        134: "Success doesn’t come to you. You go to it. — Marva Collins",
        135: "The only true wisdom is in knowing you know nothing. — Socrates",
        136: "Formal education will make you a living. Self-education will make you a fortune. — Jim Rohn",
        137: "Success usually comes to those who are too busy to be looking for it. — Henry David Thoreau",
        138: "The only place where success comes before work is in the dictionary. — Vince Lombardi",
        139: "Success is a ladder you cannot climb with your hands in your pockets. — Zig Ziglar",
        140: "I have learned that success is to be measured not so much by the position one has reached in life as by the obstacles which he has overcome while trying to succeed. — Booker T. Washington",
        141: "In life, there is no greater pleasure than the satisfaction of overcoming difficulties on the way to success. — Samuel Johnson",
        142: "To succeed, we must first believe that we can. — Nikos Kazantzakis",
        143: "The limits of the possible are only an illusion. — Carlos Castaneda",
        144: "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one that has opened for us. — Helen Keller",
        145: "Goals are the fuel in the furnace of achievement. — Brian Tracy",
        146: "What you get by achieving your goals is not as important as what you become by achieving your goals. — Zig Ziglar",
        147: "Discipline is the choice to do what you don't want to do in order to achieve what you really want. — John Maxwell",
        148: "Cherish your visions and dreams as they are the children of your soul, the blueprints of your ultimate achievements. — Napoleon Hill",
        149: "The better you feel about yourself, the higher your self-esteem, and the greater your goals and achievements in life. — Brian Tracy",
        150: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. — Ralph Waldo Emerson",
        151: "Hard times create strong men. Strong men create good times. — G. Michael Hopf",
        152: "Doubt is the beginning of wisdom. — Aristotle",
        153: "You become what you believe. — Oprah Winfrey",
        154: "Words have the power to change perception of reality. — Tony Robbins",
        155: "The best way to predict the future is to create it. — Abraham Lincoln",
        156: "Failure is the condiment that gives success its flavor. — Truman Capote",
        157: "Ideas are capital that never perish. — Karl Marx",
        158: "Inspiration exists, but it has to find you working. — Pablo Picasso",
        159: "The secret of genius is hard work, perseverance, and common sense. — Thomas Edison",
        160: "The most dangerous poison is the feeling of impunity. — Fyodor Dostoevsky",
        161: "The purpose of art is to cleanse the soul of everyday life. — Kazimir Malevich",
        162: "Within every human is a sun. Just let it shine. — Socrates",
        163: "Passion is the energy that feels power. — Bill Gates",
        164: "The mind, once stretched by a new idea, never returns to its original dimensions. — Albert Einstein",
        165: "Trust is a luxury that must be earned. — Sergey Brin",
        166: "Laughter is the sun that drives winter from the human face. — Victor Hugo",
        167: "True power is the ability to turn desires into reality. — George R.R. Martin",
        168: "Silence is the last scream of the soul. — Friedrich Nietzsche",
        169: "Conquering fear is the beginning of wisdom. — Bertrand Russell",
        170: "Creativity requires the courage to let go of certainties. — Erich Fromm",
        171: "Happiness depends upon ourselves. — Aristotle",
        172: "The only true wisdom is in knowing you know nothing. — Socrates",
        173: "The unexamined life is not worth living. — Socrates",
        174: "We are what we repeatedly do. Excellence, then, is not an act, but a habit. — Aristotle",
        175: "Man is the measure of all things. — Protagoras",
        176: "Well-being is attained little by little, and nevertheless is no little thing itself. — Zeno of Citium",
        177: "Death does not concern us, because as long as we exist, death is not here. And when it does come, we no longer exist. — Epicurus",
        178: "He has the most who is most content with the least. — Diogenes",
        179: "To learn is not only to find information but to transform oneself. — Plato",
        180: "Freedom is the power to act or not to act, and so to lay hold of good or to avoid evil. — Epictetus",
        181: "It is not what happens to you, but how you react to it that matters. — Epictetus",
        182: "Justice means minding your own business and not meddling with other people’s concerns. — Plato",
        183: "He who is not a good servant will not be a good master. — Aristotle",
    }
};

export default quotes;