const translateConstellation = {
    "en": {
        Aries: "In Aries constellation.",
        Taurus: "In Taurus constellation.",
        Gemini: "In Gemini constellation.",
        Cancer: "In Cancer constellation.",
        Leo: "In Leo constellation.",
        Virgo: "In Virgo constellation.",
        Libra: "In Libra constellation.",
        Scorpius: "In Scorpius constellation.",
        Sagittarius: "In Sagittarius constellation.",
        Capricornus: "In Capricornus constellation.",
        Aquarius: "In Aquarius constellation.",
        Pisces: "In Pisces constellation.",
        Auriga: "In Auriga constellation.",
        Ophiuchus: "In Ophiuchus constellation.",
        Cetus: "In Cetus constellation.",
        Orion: "In Orion constellation.",
        Sextans: "In Sextans constellation.",
    },
    "ru": {
        Aries: "В созвездии Овна.",
        Taurus: "В созвездии Тельца.",
        Gemini: "В созвездии Близнецов.",
        Cancer: "В созвездии Рака.",
        Leo: "В созвездии Льва.",
        Virgo: "В созвездии Девы.",
        Libra: "В созвездии Весов.",
        Scorpius: "В созвездии Скорпиона.",
        Sagittarius: "В созвездии Стрельца.",
        Capricornus: "В созвездии Козерога.",
        Aquarius: "В созвездии Водолея.",
        Pisces: "В созвездии Рыбы.",
        Auriga: "В созвездии Возничего.",
        Ophiuchus: "В созвездии Змееносца.",
        Cetus: "В созвездии Кита.",
        Orion: "В созвездии Ориона.",
        Sextans: "В созвездии Секстанта.",
    },
    "cz": {
        Aries: "V souhvězdí Berana.",
        Taurus: "V souhvězdí Býka.",
        Gemini: "V souhvězdí Blíženců.",
        Cancer: "V souhvězdí Raka.",
        Leo: "V souhvězdí Lva.",
        Virgo: "V souhvězdí Panny.",
        Libra: "V souhvězdí Vah.",
        Scorpius: "V souhvězdí Štíra.",
        Sagittarius: "V souhvězdí Střelce.",
        Capricornus: "V souhvězdí Kozoroha.",
        Aquarius: "V souhvězdí Vodnáře.",
        Pisces: "V souhvězdí Ryb.",
        Auriga: "V souhvězdí Vozky.",
        Ophiuchus: "V souhvězdí Hadonoše.",
        Cetus: "V souhvězdí Velryby.",
        Orion: "V souhvězdí Oriona.",
        Sextans: "V souhvězdí Sextantu.",
    }
}

export default translateConstellation;