const localization = {
    "en": {
        "phaseTitle": "Moon Phase",
        "commonInfoTitle": "General Information",
        "commonInfoDescFirst": "The lunar cycle is the regular change in the visible illumination of the Moon, caused by its orbital motion around the Earth and the shifting angles of sunlight. The Moon is always facing Earth with one side due to tidal locking: its rotation is synchronized with its orbit around Earth, so its rotational period matches its orbital period. This is a result of gravitational interactions that have gradually slowed its rotation.",
        "commonInfoDescSecond": "Lunar eclipses occur when the Earth is positioned between the Moon and the Sun, causing its shadow to fully or partially obscure the Moon. The shading in Moon phases happens due to the angle of illumination: part of the Moon falls into shadow while the Sun illuminates another portion of its surface.",
        "commonInfoDescLast": "The Moon plays a key role in forming tides on Earth due to its gravity. Tidal forces arise from differences in the Moon’s gravitational pull on different parts of the Earth. This causes the oceans to stretch, forming tidal bulges—one on the side closest to the Moon and another on the opposite side. Due to Earth's rotation, tides occur twice a day. During the full and new moon, tides are especially high (spring tides) due to the combined influence of the Sun and Moon. In the first and last quarters, neap tides occur, which are weaker because the Sun's gravity partially counteracts the Moon’s influence.",
        "cycleButton": "Lunar Cycle",
        "moonHistoryTitle": "The Moon in Myths and Astrology",
        "moonHistoryDescFirst": "The full moon is often associated with heightened emotions, intuition, and even restlessness, whereas the new moon is considered a time for renewal, reflection, and setting new intentions. In Ancient Greece, the Moon was linked to the goddesses Artemis and Selene, seen as patrons of the night and life cycles. In Chinese culture, the Moon symbolized harmony and family ties, especially during the Mid-Autumn Festival. Among the Slavs, the Moon was regarded as a mystical force influencing harvests, fate, and magical rituals.",
        "moonHistoryDescSecond": "As the Moon waxes, its energy strengthens, peaking at the full moon. This is a period of emotional intensity, energy surges, and cycle completions. Fire signs (Aries, Leo, Sagittarius) feel a rise in passion and motivation but may become impulsive. Earth signs (Taurus, Virgo, Capricorn) focus on results and evaluations but may experience inner restlessness. Air signs (Gemini, Libra, Aquarius) feel an increase in ideas and communication but emotions might get overwhelming. Water signs (Cancer, Scorpio, Pisces) become highly sensitive, intuition sharpens, but mood swings can occur.",
        "moonHistoryDescLast": "During the waning moon, energy diminishes, marking a time for completion, rest, and preparation for a new cycle. This is a moment for reflection and new beginnings. Fire signs instinctively feel the need to set new goals and regain strength. Earth signs seek stability, analyze past mistakes, and make long-term plans. Air signs reduce social activity, focusing on inner processes. Water signs delve into emotions and seek meaning, possibly feeling a need for solitude."
    },
    "ru": {
        "phaseTitle": "Фаза луны.",
        "commonInfoTitle": "Общая информация.",
        "commonInfoDescFirst": "Лунный цикл — это регулярное изменение видимого освещения Луны, вызванное её орбитальным движением вокруг Земли и сменой углов освещения Солнцем. Луна всегда повернута к Земле одной стороной из-за приливного захвата: её вращение синхронизировано с орбитой вокруг Земли, поэтому период её вращения вокруг своей оси совпадает с периодом её обращения вокруг планеты. Это результат гравитационного взаимодействия, которое постепенно замедлило её вращение",
        "commonInfoDescSecond": "Лунные затмения происходят, когда Земля находится между Луной и Солнцем, и её тень полностью или частично закрывает Луну. А затенение в фазах Луны происходит из-за угла освещения: часть Луны оказывается в тени, пока Солнце освещает другую часть её поверхности.",
        "commonInfoDescLast": "Луна играет ключевую роль в формировании приливов и отливов на Земле благодаря своей гравитации. Приливные силы возникают из-за разницы в гравитационном притяжении Луны к разным частям Земли. Это приводит к тому, что океаны растягиваются, образуя приливные бугры — один на стороне, ближайшей к Луне, и другой на противоположной стороне. Из-за вращения Земли приливы происходят дважды в сутки. При полной и новой Луне приливы становятся особенно высокими (сизигийные приливы) из-за совокупного влияния Солнца и Луны. А в первой и последней четверти возникают квадратурные приливы, которые слабее, потому что гравитация Солнца частично компенсирует влияние Луны.",
        "cycleButton": "Лунный цикл",
        "moonHistoryTitle": "Луна в мифах и астрологии.",
        "moonHistoryDescFirst": "Луна в полнолуние часто связывается с усилением эмоций, интуиции и даже беспокойства, тогда как новолуние считается временем обновления, размышлений и закладывания новых начинаний. В Древней Греции Луну ассоциировали с богинями Артемидой и Селеной, считая их покровительницами ночи и циклов жизни. В китайской культуре Луна символизировала гармонию и семейные узы, особенно во время Праздника середины осени. У славян Луна воспринималась как магическая сила, влияющая на урожай, судьбу и мистические обряды.",
        "moonHistoryDescSecond": "Когда Луна растёт, её энергия становится сильнее, достигая кульминации в полнолуние. Это период эмоциональной напряжённости, всплесков энергии и завершения циклов. Огненные знаки (Овен, Лев, Стрелец) – чувствуют прилив страсти и мотивации, но могут стать импульсивнее. Земные знаки (Телец, Дева, Козерог) – концентрируются на результатах и подводят итоги, но могут ощущать внутреннее беспокойство. Воздушные знаки (Близнецы, Весы, Водолей) – усиливается поток идей и общения, но эмоции могут выйти из-под контроля. Водные знаки (Рак, Скорпион, Рыбы) – становятся особенно чувствительными, интуиция обостряется, но возможны перепады настроения.",
        "moonHistoryDescLast": "В период убывающей Луны энергия снижается, наступает время завершения, отдыха и подготовки к новому циклу. Это момент для размышлений и новых начинаний. Огненные знаки – интуитивно ощущают необходимость ставить новые цели и набираются сил. Земные знаки – стремятся к стабилизации, анализируют прошлые ошибки и строят долгосрочные планы. Воздушные знаки – снижают активность в общении, сосредотачиваясь на внутренних процессах. Водные знаки – погружаются в эмоции и поиск смысла, могут чувствовать потребность в уединении.",
    },
    "cz": {
        "phaseTitle": "Fáze Měsíce",
        "commonInfoTitle": "Obecné informace",
        "commonInfoDescFirst": "Měsíční cyklus je pravidelná změna viditelného osvětlení Měsíce způsobená jeho oběžným pohybem kolem Země a změnou úhlů osvětlení Sluncem. Měsíc je vždy otočen k Zemi jednou stranou kvůli slapovému zámku: jeho rotace je synchronizována s oběhem kolem Země, takže doba jeho rotace odpovídá době oběhu. To je výsledek gravitačních interakcí, které postupně zpomalily jeho rotaci.",
        "commonInfoDescSecond": "Měsíční zatmění nastává, když je Země mezi Měsícem a Sluncem, a její stín zcela nebo částečně zakrývá Měsíc. Zastínění ve fázích Měsíce nastává kvůli úhlu osvětlení: část Měsíce se ocitá ve stínu, zatímco Slunce osvětluje jinou část jeho povrchu.",
        "commonInfoDescLast": "Měsíc hraje klíčovou roli při vzniku přílivu a odlivu na Zemi díky své gravitaci. Slapové síly vznikají v důsledku rozdílu v gravitačním přitahování Měsíce k různým částem Země. To způsobuje natahování oceánů, čímž se vytvářejí slapové hřebeny – jeden na straně nejblíže k Měsíci a druhý na opačné straně. Kvůli rotaci Země dochází k přílivu dvakrát denně. Při úplňku a novoluní jsou přílivy obzvláště vysoké (sizigijní přílivy) díky kombinovanému vlivu Slunce a Měsíce. Při první a poslední čtvrti vznikají kvadraturní přílivy, které jsou slabší, protože gravitace Slunce částečně kompenzuje vliv Měsíce.",
        "cycleButton": "Měsíční cyklus",
        "moonHistoryTitle": "Měsíc v mýtech a astrologii",
        "moonHistoryDescFirst": "Úplněk je často spojován se zesílenými emocemi, intuicí a někdy i neklidem, zatímco novoluní je považováno za čas obnovy, rozjímání a zahájení nových začátků. Ve starověkém Řecku byl Měsíc spojován s bohyněmi Artemidou a Seléné, které byly patronkami noci a životních cyklů. V čínské kultuře Měsíc symbolizoval harmonii a rodinné vazby, zejména během Svátku středu podzimu. Slované vnímali Měsíc jako magickou sílu ovlivňující úrodu, osud a mystické rituály.",
        "moonHistoryDescSecond": "Jak Měsíc roste, jeho energie zesiluje a vrcholí při úplňku. Toto období je charakteristické emocionálním napětím, energetickými vlnami a uzavíráním cyklů. Ohnivá znamení (Beran, Lev, Střelec) pociťují nárůst vášně a motivace, ale mohou být impulzivnější. Zemská znamení (Býk, Panna, Kozoroh) se soustředí na výsledky, ale mohou cítit vnitřní neklid. Vzdušná znamení (Blíženci, Váhy, Vodnář) zažívají příval myšlenek a komunikace, ale emoce mohou být intenzivní. Vodní znamení (Rak, Štír, Ryby) jsou zvlášť citlivá, intuice se zostřuje, ale mohou se objevit výkyvy nálad.",
        "moonHistoryDescLast": "Během ubývajícího Měsíce energie slábne, nastává čas dokončování, odpočinku a přípravy na nový cyklus. Je to chvíle pro rozjímání a nové začátky. Ohnivá znamení intuitivně cítí potřebu stanovit nové cíle a nabrat sílu. Zemská znamení hledají stabilitu, analyzují minulé chyby a plánují dlouhodobě. Vzdušná znamení omezují sociální aktivitu a soustředí se na vnitřní procesy. Vodní znamení se ponořují do emocí a hledání smyslu, mohou cítit potřebu samoty."
    }
}

export default localization;