const retrogradMercuryDates = [
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2025-03-15",
        "end": "2025-04-07",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2025-07-18",
        "end": "2025-08-11",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2025-11-09",
        "end": "2025-04-29",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2026-02-26",
        "end": "2026-03-20",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2026-06-29",
        "end": "2026-07-23",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2026-10-24",
        "end": "2026-11-13",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2027-02-09",
        "end": "2027-03-03",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2027-06-10",
        "end": "2027-07-04",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2027-10-07",
        "end": "2027-10-28",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2028-01-24",
        "end": "2028-02-14",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2028-05-21",
        "end": "2028-06-14",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2028-09-19",
        "end": "2028-10-11",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2029-01-07",
        "end": "2029-01-27",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2029-05-01",
        "end": "2029-05-25",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2029-09-02",
        "end": "2029-09-25",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2029-12-22",
        "end": "2030-01-11",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2030-04-13",
        "end": "2030-05-06",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2030-08-16",
        "end": "2030-09-08",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2030-12-06",
        "end": "2030-12-25",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2031-03-26",
        "end": "2031-04-18",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2031-07-29",
        "end": "2031-08-22",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2031-11-19",
        "end": "2031-12-09",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2032-03-07",
        "end": "2032-03-30",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2032-07-10",
        "end": "2032-08-03",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2032-11-02",
        "end": "2032-11-22",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2033-02-18",
        "end": "2033-03-13",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2033-06-21",
        "end": "2033-07-15",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2033-10-16",
        "end": "2033-11-06",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2034-02-02",
        "end": "2034-02-23",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2034-06-02",
        "end": "2034-06-26",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2034-09-30",
        "end": "2034-10-21",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2035-01-17",
        "end": "2035-02-07",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2035-05-13",
        "end": "2035-06-06",
    },
    {
        "name": "Retrograd Mercury",
        "picture": "./assets/images/events/retrogradeMercury.jpg",
        "date": "2035-09-13",
        "end": "2035-10-05",
    }
];

export default retrogradMercuryDates;