const localization = {
    "en": {
        "usTitle": "About Us",
        "usDescription": "Welcome to our app! Here, cosmic phenomena and astrology come to life, transforming into a fascinating and educational experience. We create a space where everyone can enjoy the magic of the Universe, learn something new, and simply take pleasure in interacting with unique content. Our app is designed for entertainment and does not intend to offend or harm anyone, regardless of nationality, religion, or beliefs. We also do not encourage any illegal or unethical actions. All data provided by the app is for informational purposes only, helping you enjoy astrology and cosmic phenomena in a comfortable and safe format.",
        "missionTitle": "Our Mission",
        "missionDescription": "We strive to help you find harmony between your inner world and the rhythms of the Universe. We believe that understanding astrology and cosmic events can bring clarity to your thoughts, confidence in decision-making, and harmony in your personal life. Our project stands out with its personalized approach, high-quality standards, and attention to detail. We believe that every little thing matters.",
        "teamTitle": "Our Team",
        "teamDescription": "This project was born out of a passion for astrology, space, mythology, and the desire to share this knowledge with the world. The core work has been done by the developer, whose energy and creativity were fueled by inspiration from his spouse and like-minded friends. Together, they created a space where every detail reflects their passion and dedication to their craft. Our team consists of a visionary developer, his spouse, who played a key role in support and creative impulses, and friends who contributed their ideas. Together, we combined our efforts to create a project that brings joy and knowledge to users.",
        "connectTitle": "Contact Us",
        "mail": "Email:",
        "instagram": "Follow us:",
        "threads": "Read us:",
        "telegram": "Subscribe to us:",
        "thanksTitle": "Gratitude",
    },
    "ru": {
        "usTitle": "О нас",
        "usDescription": "Добро пожаловать в наше приложение! Здесь космические явления и астрология оживают, превращаясь в увлекательный и познавательный опыт. Мы создаем пространство, где каждый может насладиться магией Вселенной, узнать что-то новое и просто получить удовольствие от взаимодействия с уникальным контентом. Наше приложение создано для развлечения и не стремится задеть или оскорбить чувства людей, независимо от их национальности, вероисповедания или взглядов. Мы также не поощряем никаких противоправных или неэтичных действий. Все данные, предоставляемые приложением, носят ознакомительный характер, чтобы помочь вам насладиться астрологией и космическими явлениями в комфортном и безопасном формате.",
        "missionTitle": "Наша миссия",
        "missionDescription": "Мы стремимся помочь вам найти гармонию между внутренним миром и ритмами Вселенной. Мы верим, что понимание астрологии и космических событий может дать ясность в размышлениях, уверенность в принятии решений и гармонию в личной жизни. Наш проект отличается индивидуальным подходом, высокими стандартами качества и любовью к деталям. Мы верим, что каждая мелочь имеет значение.",
        "teamTitle": "Наша команда",
        "teamDescription": "Этот проект родился из увлечения астрологией, космосом, мифологией и стремления поделиться этими знаниями с миром. Основная часть работы выполнена разработчиком, чья энергия и творчество подпитывались вдохновением, полученным от супруги и товарищей, разделяющих его идеи. Вместе они создали пространство, где каждая деталь отражает страсть и преданность своему делу. Наша команда состоит из вдохновленного разработчика, его супруги, сыгравшей ключевую роль в поддержке и креативных импульсах, и товарищей, которые внесли свой идейный вклад. Вместе мы объединили усилия, чтобы создать проект, который дарит удовольствие и знания пользователям.",
        "connectTitle": "Свяжитесь с нами",
        "mail": "Электронная почта:",
        "instagram": "Следите за нами:",
        "threads": "Читайте нас:",
        "telegram": "Подписывайтесь на нас:",
        "thanksTitle": "Благодарность",
    },
    "cz": {
        "usTitle": "O nás",
        "usDescription": "Vítejte v naší aplikaci! Zde ožívají kosmické jevy a astrologie, proměňují se ve fascinující a poučný zážitek. Vytváříme prostor, kde si každý může užít kouzlo vesmíru, naučit se něco nového a jednoduše si užít interakci s unikátním obsahem. Naše aplikace je určena pro zábavu a nemá v úmyslu nikoho urazit nebo poškodit, bez ohledu na národnost, náboženství nebo přesvědčení. Také nepodporujeme žádné nelegální nebo neetické jednání. Veškeré údaje poskytované aplikací jsou pouze informativní, aby vám pomohly užít si astrologii a kosmické jevy v pohodlném a bezpečném formátu.",
        "missionTitle": "Naše mise",
        "missionDescription": "Snažíme se vám pomoci najít harmonii mezi vaším vnitřním světem a rytmy vesmíru. Věříme, že pochopení astrologie a kosmických událostí může přinést jasnost do vašich myšlenek, sebejistotu při rozhodování a harmonii v osobním životě. Náš projekt vyniká individuálním přístupem, vysokými standardy kvality a láskou k detailům. Věříme, že na každém drobném prvku záleží.",
        "teamTitle": "Náš tým",
        "teamDescription": "Tento projekt se zrodil z vášně pro astrologii, vesmír, mytologii a touhy sdílet tyto znalosti se světem. Hlavní část práce odvedl vývojář, jehož energie a kreativita byly podpořeny inspirací od jeho partnerky a přátel, kteří sdíleli jeho vizi. Společně vytvořili prostor, kde každý detail odráží jejich nadšení a oddanost svému řemeslu. Náš tým tvoří vizionářský vývojář, jeho partnerka, která sehrála klíčovou roli v podpoře a kreativních impulzech, a přátelé, kteří přispěli svými nápady. Společně jsme spojili síly, abychom vytvořili projekt, který přináší radost a znalosti uživatelům.",
        "connectTitle": "Kontaktujte nás",
        "mail": "E-mail:",
        "instagram": "Sledujte nás:",
        "threads": "Čtěte nás:",
        "telegram": "Přihlaste se k odběru:",
        "thanksTitle": "Vděčnost",
    },
}

export default localization;