const localization = {
    "en": {
        "bannerFirst": "Luory — your personal astrologer.",
        "bannerSecond": "We invite you to uncover the mysteries of the cosmos.",
        "bannerThird": "Discover yourself through the interaction of celestial bodies.",
        "bannerLast": "Take a step towards the stars with Luory!",
        "starDanceTitle": "The dance of stars and the Moon: What lies ahead?",
        "starDanceDescription": "The cosmos moves in an eternal rhythm. The universe is born, expands, fades, and is reborn again. Everything has happened before, everything will disappear and return again in an infinite cycle.",
        "moonLinkDescription": "Uncover the mysteries of the future — explore the position of the Moon and its meaning.",
        "moonLinkBtn": "Moon position",
        "eventsLinkDescription": "Upcoming events influence us. Find out what is about to happen.",
        "eventsLinkBtn": "Events",
        "constellationTitle": "Constellations of fate: the magic of signs and their interactions.",
        "constellationDescription": "Unveil the secrets of the influence of constellations! Discover how zodiac signs shape your destiny and what astrological interactions determine harmony and balance. Choose the path of understanding — explore the descriptions of the signs or their connections. The stars speak — all that remains is to hear them. Explore the influence of the signs and their magic!",
        "signsLinkDescription": "Discover the secrets of the zodiac signs.",
        "signsLinkBtn": "Explore signs",
        "interactionLinkDescription": "Find out how signs interact with each other.",
        "interactionLinkBtn": "Unlock connections",
        "horoscopeLinkDescription": "The stars have pointed the direction, but the choice of how to walk the path is yours.",
        "horoscopeLinkBtn": "Horoscope",
        "contactsTitle": "Our contacts.",
        "mail": "Email:",
        "instagram": "Follow us:",
        "threads": "Read us:",
        "telegram": "Subscribe to us:",
    },
    "ru": {
        "bannerFirst": "Luory — ваш персональный астролог.",
        "bannerSecond": "Мы приглашаем вас раскрыть тайны космоса.",
        "bannerThird": "Познайте себя через взаимодействие небесных тел.",
        "bannerLast": "Сделайте шаг к звездам вместе с Luory!",
        "starDanceTitle": "Танец звезд и луны: что ждет впереди?",
        "starDanceDescription": "Космос движется в вечном ритме. Вселенная рождается, расширяется, угасает и возрождается вновь. Всё уже было, всё исчезнет и вернётся снова в бесконечном цикле.",
        "moonLinkDescription": "Откройте тайны грядущего — исследуйте положение Луны и ее значение.",
        "moonLinkBtn": "Положение луны",
        "eventsLinkDescription": "Грядущие события оказывают на нас влияние. Узнайте о том, что скоро случится.",
        "eventsLinkBtn": "События",
        "constellationTitle": "Созвездия судьбы: магия знаков и их взаимодействие.",
        "constellationDescription": "Откройте завесу тайны влияния созвездий! Узнайте, как знаки зодиака формируют вашу судьбу и какие астрологические взаимодействия определяют гармонию и баланс. Выберите путь понимания — загляните в описание знаков или исследуйте их взаимосвязь. Звезды говорят — осталось лишь услышать их. Исследуйте влияние знаков и их магию!",
        "signsLinkDescription": "Откройте для себя тайны знаков зодиака.",
        "signsLinkBtn": "Исследовать знаки",
        "interactionLinkDescription": "Узнайте, как взаимодействуют знаки между собой.",
        "interactionLinkBtn": "Открыть взаимосвязи",
        "horoscopeLinkDescription": "Звёзды указали направление, выбор, как пройти этот путь, за тобой.",
        "horoscopeLinkBtn": "Гороскоп",
        "contactsTitle": "Наши контакты.",
        "mail": "Электронная почта:",
        "instagram": "Следите за нами:",
        "threads": "Читайте нас:",
        "telegram": "Подписывайтесь на нас:",
    },
    "cz": {
        "bannerFirst": "Luory — váš osobní astrolog.",
        "bannerSecond": "Zveme vás k odhalení tajemství vesmíru.",
        "bannerThird": "Poznejte sami sebe skrze interakci nebeských těles.",
        "bannerLast": "Udělejte krok ke hvězdám s Luory!",
        "starDanceTitle": "Tanec hvězd a Měsíce: Co vás čeká?",
        "starDanceDescription": "Vesmír se pohybuje v věčném rytmu. Vesmír se rodí, rozpíná, slábne a znovu se rodí. Vše už se stalo, vše zmizí a opět se vrátí v nekonečném cyklu.",
        "moonLinkDescription": "Odhalte tajemství budoucnosti – prozkoumejte polohu Měsíce a její význam.",
        "moonLinkBtn": "Poloha Měsíce",
        "eventsLinkDescription": "Nadcházející události nás ovlivňují. Zjistěte, co se brzy stane.",
        "eventsLinkBtn": "Události",
        "constellationTitle": "Souhvězdí osudu: Magie znamení a jejich interakce.",
        "constellationDescription": "Odhalte tajemství vlivu souhvězdí! Zjistěte, jak znamení zvěrokruhu utvářejí váš osud a jaké astrologické interakce určují harmonii a rovnováhu. Vyberte cestu porozumění – prozkoumejte popis znamení nebo jejich propojení. Hvězdy promlouvají – stačí je jen slyšet. Prozkoumejte vliv znamení a jejich magii!",
        "signsLinkDescription": "Objevte tajemství znamení zvěrokruhu.",
        "signsLinkBtn": "Prozkoumat znamení",
        "interactionLinkDescription": "Zjistěte, jak znamení vzájemně interagují.",
        "interactionLinkBtn": "Odemknout spojení",
        "horoscopeLinkDescription": "Hvězdy ukázaly směr, ale volba cesty je na vás.",
        "horoscopeLinkBtn": "Horoskop",
        "contactsTitle": "Naše kontakty.",
        "mail": "E-mail:",
        "instagram": "Sledujte nás:",
        "threads": "Čtěte nás:",
        "telegram": "Přihlaste se k odběru:",
    },
}

export default localization;