const interactionDescription = {
    "Aries": {
        "Aries": {
            "Elements": "Огонь + Огонь",
            "Modes": "Кардинальный + Кардинальный",
            "Polarities": "Мужская + Мужская",
            "Romance": "Страстные отношения, но возможны конфликты из-за борьбы за лидерство.",
            "RomanceScore": 3,
            "Friendship": "Энергичные авантюры и взаимная поддержка.",
            "FriendshipScore": 4,
            "Work": "Конкуренция и столкновение амбиций.",
            "WorkScore": 2,
            "Advice": "«Учитесь делегировать задачи и уступать в спорах».",
        },
        "Taurus": {
            "Elements": "Огонь + Земля",
            "Modes": "Кардинальный + Фиксированный",
            "Polarities": "Мужская + Женская",
            "Romance": "Овен стремится к скорости, Телец — к стабильности.",
            "RomanceScore": 2,
            "Friendship": "Общие интересы, но разный темп жизни.",
            "FriendshipScore": 3,
            "Work": "Рискованные идеи Овна против консерватизма Тельца.",
            "WorkScore": "1",
            "Advice": "«Найдите компромисс между действием и терпением».",
        },
        "Gemini": {
            "Elements": "Огонь + Воздух",
            "Modes": "Кардинальный + Мутабельный",
            "Polarities": "Мужская + Мужская",
            "Romance": "Динамичный союз с интеллектуальной связью.",
            "RomanceScore": 4,
            "Friendship": "Идеальные партнеры для путешествий и общения.",
            "FriendshipScore": 5,
            "Work": "Креативность и быстрая реализация проектов.",
            "WorkScore": 4,
            "Advice": "«Избегайте поверхностности в серьезных вопросах».",
        },
        "Cancer": {
            "Elements": "Огонь + Вода",
            "Modes": "Кардинальный + Кардинальный",
            "Polarities": "Мужская + Женская",
            "Romance": "Овен резок, Рак чувствителен.",
            "RomanceScore": 2,
            "Friendship": "Нуждаются в времени для адаптации друг к другу.",
            "FriendshipScore": 3,
            "Work": "Разные подходы: импульсивность против эмоциональности.",
            "WorkScore": 2,
            "Advice": "«Уважайте личные границы и чувства».",
        },
        "Leo": {
            "Elements": "Огонь + Огонь",
            "Modes": "Кардинальный + Фиксированный",
            "Polarities": "Мужская + Мужская",
            "Romance": "Яркие эмоции и взаимное восхищение.",
            "RomanceScore": 4,
            "Friendship": "Идеальный тандем для активного отдыха.",
            "FriendshipScore": 5,
            "Work": "Конкуренция за роль лидера.",
            "WorkScore": 3,
            "Advice": "«Фокусируйтесь на общих целях, а не на амбициях».",
        },
        "Virgo": {
            "Elements": "Огонь + Земля",
            "Modes": "Кардинальный + Мутабельный",
            "Polarities": "Мужская + Женская",
            "Romance": "Овен импульсивен, Дева критична.",
            "RomanceScore": 2,
            "Friendship": "Возможна, если найдут общее хобби.",
            "FriendshipScore": 3,
            "Work": "Овен генерирует идеи, Дева их систематизирует.",
            "WorkScore": 3,
            "Advice": "«Цените внимание к деталям».",
        },
        "Libra": {
            "Elements": "Огонь + Воздух",
            "Modes": "Кардинальный + Кардинальный",
            "Polarities": "Мужская + Мужская",
            "Romance": "Гармония в романтике и активности.",
            "RomanceScore": 4,
            "Friendship": "Отличные партнеры для социальных мероприятий.",
            "FriendshipScore": 4,
            "Work": "Весы сомневаются, Овен действует.",
            "WorkScore": 3,
            "Advice": "«Не игнорируйте диалог и компромиссы».",
        },
        "Scorpio": {
            "Elements": "Огонь + Вода",
            "Modes": "Кардинальный + Фиксированный",
            "Polarities": "Мужская + Женская",
            "Romance": "Страсть есть, но возможны ревность и конфликты.",
            "RomanceScore": 3,
            "Friendship": "Разные ценности и уровень доверия.",
            "FriendshipScore": 2,
            "Work": "Скорпион-стратег vs. Овен-импульсивный.",
            "WorkScore": 2,
            "Advice": "«Избегайте скрытых манипуляций».",
        },
        "Sagittarius": {
            "Elements": "Огонь + Огонь",
            "Modes": "Кардинальный + Мутабельный",
            "Polarities": "Мужская + Мужская",
            "Romance": "Идеальная совместимость в любви и приключениях.",
            "RomanceScore": 5,
            "Friendship": "Оптимизм, юмор и общие цели.",
            "FriendshipScore": 5,
            "Work": "Энергия и масштабные проекты.",
            "WorkScore": 4,
            "Advice": "«Не упускайте из виду детали».",
        },
        "Capricorn": {
            "Elements": "Огонь + Земля",
            "Modes": "Кардинальный + Кардинальный",
            "Polarities": "Мужская + Женская",
            "Romance": "Овен хочет быстрых результатов, Козерог — долгосрочных.",
            "RomanceScore": 2,
            "Friendship": "Возможна при общих амбициях.",
            "FriendshipScore": 3,
            "Work": "Овен вдохновляет, Козерог структурирует.",
            "WorkScore": 3,
            "Advice": "«Учитесь планировать на перспективу».",
        },
        "Aquarius": {
            "Elements": "Огонь + Воздух",
            "Modes": "Кардинальный + Фиксированный",
            "Polarities": "Мужская + Мужская",
            "Romance": "Инновации, свобода и взаимное уважение.",
            "RomanceScore": 4,
            "Friendship": "Единство нестандартных идей.",
            "FriendshipScore": 5,
            "Work": "Креативность и эксперименты.",
            "WorkScore": 4,
            "Advice": "«Не нарушайте личные границы».",
        },
        "Pisces": {
            "Elements": "Огонь + Вода",
            "Modes": "Кардинальный + Мутабельный",
            "Polarities": "Мужская + Женская",
            "Romance": "Овен прямолинеен, Рыбы — мечтательны.",
            "RomanceScore": 2,
            "Friendship": "Возможна, если Овен проявит эмпатию.",
            "FriendshipScore": 3,
            "Work": "Разные подходы: действие vs. созерцание.",
            "WorkScore": 2,
            "Advice": "«Поддерживайте Рыб в их идеях».",
        },
    },
    "Taurus": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
    },
    "Gemini": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
    },
    "Cancer": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
    },
    "Leo": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
    },
    "Virgo": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
    },
    "Libra": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
    },
    "Scorpio": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
    },
    "Sagittarius": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
    },
    "Capricorn": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
    },
    "Aquarius": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
    },
    "Pisces": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
    },
}