const interactionDescription = {
    "Aries": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
    },
    "Taurus": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
    },
    "Gemini": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
    },
    "Cancer": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
    },
    "Leo": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
    },
    "Virgo": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
    },
    "Libra": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
    },
    "Scorpio": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
    },
    "Sagittarius": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
    },
    "Capricorn": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
    },
    "Aquarius": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
    },
    "Pisces": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "Friendship": "",
            "Work": "",
            "Advice": "",
        },
    },
}