const interactionDescription = {
    "Aries": {
        "Aries": {
            "Elements": "Огонь + Огонь",
            "Modes": "Кардинальный + Кардинальный",
            "Polarities": "Мужская + Мужская",
            "Romance": "Страстные отношения, но возможны конфликты из-за борьбы за лидерство.",
            "RomanceScore": 3,
            "Friendship": "Энергичные авантюры и взаимная поддержка.",
            "FriendshipScore": 4,
            "Work": "Конкуренция и столкновение амбиций.",
            "WorkScore": 2,
            "Advice": "«Учитесь делегировать задачи и уступать в спорах».",
        },
        "Taurus": {
            "Elements": "Огонь + Земля",
            "Modes": "Кардинальный + Фиксированный",
            "Polarities": "Мужская + Женская",
            "Romance": "Овен стремится к скорости, Телец — к стабильности.",
            "RomanceScore": 2,
            "Friendship": "Общие интересы, но разный темп жизни.",
            "FriendshipScore": 3,
            "Work": "Рискованные идеи Овна против консерватизма Тельца.",
            "WorkScore": 1,
            "Advice": "«Найдите компромисс между действием и терпением».",
        },
        "Gemini": {
            "Elements": "Огонь + Воздух",
            "Modes": "Кардинальный + Мутабельный",
            "Polarities": "Мужская + Мужская",
            "Romance": "Динамичный союз с интеллектуальной связью.",
            "RomanceScore": 4,
            "Friendship": "Идеальные партнеры для путешествий и общения.",
            "FriendshipScore": 5,
            "Work": "Креативность и быстрая реализация проектов.",
            "WorkScore": 4,
            "Advice": "«Избегайте поверхностности в серьезных вопросах».",
        },
        "Cancer": {
            "Elements": "Огонь + Вода",
            "Modes": "Кардинальный + Кардинальный",
            "Polarities": "Мужская + Женская",
            "Romance": "Овен резок, Рак чувствителен.",
            "RomanceScore": 2,
            "Friendship": "Нуждаются в времени для адаптации друг к другу.",
            "FriendshipScore": 3,
            "Work": "Разные подходы: импульсивность против эмоциональности.",
            "WorkScore": 2,
            "Advice": "«Уважайте личные границы и чувства».",
        },
        "Leo": {
            "Elements": "Огонь + Огонь",
            "Modes": "Кардинальный + Фиксированный",
            "Polarities": "Мужская + Мужская",
            "Romance": "Яркие эмоции и взаимное восхищение.",
            "RomanceScore": 4,
            "Friendship": "Идеальный тандем для активного отдыха.",
            "FriendshipScore": 5,
            "Work": "Конкуренция за роль лидера.",
            "WorkScore": 3,
            "Advice": "«Фокусируйтесь на общих целях, а не на амбициях».",
        },
        "Virgo": {
            "Elements": "Огонь + Земля",
            "Modes": "Кардинальный + Мутабельный",
            "Polarities": "Мужская + Женская",
            "Romance": "Овен импульсивен, Дева критична.",
            "RomanceScore": 2,
            "Friendship": "Возможна, если найдут общее хобби.",
            "FriendshipScore": 3,
            "Work": "Овен генерирует идеи, Дева их систематизирует.",
            "WorkScore": 3,
            "Advice": "«Цените внимание к деталям».",
        },
        "Libra": {
            "Elements": "Огонь + Воздух",
            "Modes": "Кардинальный + Кардинальный",
            "Polarities": "Мужская + Мужская",
            "Romance": "Гармония в романтике и активности.",
            "RomanceScore": 4,
            "Friendship": "Отличные партнеры для социальных мероприятий.",
            "FriendshipScore": 4,
            "Work": "Весы сомневаются, Овен действует.",
            "WorkScore": 3,
            "Advice": "«Не игнорируйте диалог и компромиссы».",
        },
        "Scorpio": {
            "Elements": "Огонь + Вода",
            "Modes": "Кардинальный + Фиксированный",
            "Polarities": "Мужская + Женская",
            "Romance": "Страсть есть, но возможны ревность и конфликты.",
            "RomanceScore": 3,
            "Friendship": "Разные ценности и уровень доверия.",
            "FriendshipScore": 2,
            "Work": "Скорпион-стратег vs. Овен-импульсивный.",
            "WorkScore": 2,
            "Advice": "«Избегайте скрытых манипуляций».",
        },
        "Sagittarius": {
            "Elements": "Огонь + Огонь",
            "Modes": "Кардинальный + Мутабельный",
            "Polarities": "Мужская + Мужская",
            "Romance": "Идеальная совместимость в любви и приключениях.",
            "RomanceScore": 5,
            "Friendship": "Оптимизм, юмор и общие цели.",
            "FriendshipScore": 5,
            "Work": "Энергия и масштабные проекты.",
            "WorkScore": 4,
            "Advice": "«Не упускайте из виду детали».",
        },
        "Capricorn": {
            "Elements": "Огонь + Земля",
            "Modes": "Кардинальный + Кардинальный",
            "Polarities": "Мужская + Женская",
            "Romance": "Овен хочет быстрых результатов, Козерог — долгосрочных.",
            "RomanceScore": 2,
            "Friendship": "Возможна при общих амбициях.",
            "FriendshipScore": 3,
            "Work": "Овен вдохновляет, Козерог структурирует.",
            "WorkScore": 3,
            "Advice": "«Учитесь планировать на перспективу».",
        },
        "Aquarius": {
            "Elements": "Огонь + Воздух",
            "Modes": "Кардинальный + Фиксированный",
            "Polarities": "Мужская + Мужская",
            "Romance": "Инновации, свобода и взаимное уважение.",
            "RomanceScore": 4,
            "Friendship": "Единство нестандартных идей.",
            "FriendshipScore": 5,
            "Work": "Креативность и эксперименты.",
            "WorkScore": 4,
            "Advice": "«Не нарушайте личные границы».",
        },
        "Pisces": {
            "Elements": "Огонь + Вода",
            "Modes": "Кардинальный + Мутабельный",
            "Polarities": "Мужская + Женская",
            "Romance": "Овен прямолинеен, Рыбы — мечтательны.",
            "RomanceScore": 2,
            "Friendship": "Возможна, если Овен проявит эмпатию.",
            "FriendshipScore": 3,
            "Work": "Разные подходы: действие vs. созерцание.",
            "WorkScore": 2,
            "Advice": "«Поддерживайте Рыб в их идеях».",
        },
    },
    "Taurus": {
        "Aries": {
            "Elements": "Земля + Огонь",
            "Modes": "Фиксированный + Кардинальный",
            "Polarities": "Женская + Мужская",
            "Romance": "Овен импульсивен, Телец медлителен.",
            "RomanceScore": 2,
            "Friendship": "Возможна при общих увлечениях.",
            "FriendshipScore": 3,
            "Work": "Конфликт подходов: риск против стабильности.",
            "WorkScore": 2,
            "Advice": "«Найдите баланс между действием и терпением».",
        },
        "Taurus": {
            "Elements": "Земля + Земля",
            "Modes": "Фиксированный + Фиксированный",
            "Polarities": "Женская + Женская",
            "Romance": "Стабильность и взаимопонимание, но возможна рутина.",
            "RomanceScore": 4,
            "Friendship": "Надежные партнеры с общими ценностями.",
            "FriendshipScore": 5,
            "Work": "Отличная команда для долгосрочных проектов.",
            "WorkScore": 5,
            "Advice": "«Добавьте спонтанности, чтобы избежать застоя».",
        },
        "Gemini": {
            "Elements": "Земля + Воздух",
            "Modes": "Фиксированный + Мутабельный",
            "Polarities": "Женская + Мужская",
            "Romance": "Телец хочет стабильности, Близнецы — разнообразия.",
            "RomanceScore": 2,
            "Friendship": "Общение возможно, если найти общие темы.",
            "FriendshipScore": 3,
            "Work": "Телец планирует, Близнецы импровизируют.",
            "WorkScore": 2,
            "Advice": "«Учитесь принимать различия в стиле жизни».",
        },
        "Cancer": {
            "Elements": "Земля + Вода",
            "Modes": "Фиксированный + Кардинальный",
            "Polarities": "Женская + Женская",
            "Romance": "Гармония чувств и домашнего уюта.",
            "RomanceScore": 4,
            "Friendship": "Взаимная поддержка и доверие.",
            "FriendshipScore": 4,
            "Work": "Телец практичен, Рак эмоционален.",
            "WorkScore": 3,
            "Advice": "«Не игнорируйте эмоциональные потребности Рака».",
        },
        "Leo": {
            "Elements": "Земля + Огонь",
            "Modes": "Фиксированный + Фиксированный",
            "Polarities": "Женская + Мужская",
            "Romance": "Страсть есть, но борьба за лидерство.",
            "RomanceScore": 3,
            "Friendship": "Разные интересы: Лев любит роскошь, Телец — простоту.",
            "FriendshipScore": 2,
            "Work": "Телец консервативен, Лев амбициозен.",
            "WorkScore": 2,
            "Advice": "«Ищите баланс между скромностью и яркостью».",
        },
        "Virgo": {
            "Elements": "Земля + Земля",
            "Modes": "Фиксированный + Мутабельный",
            "Polarities": "Женская + Женская",
            "Romance": "Идеальная пара: практичность и забота.",
            "RomanceScore": 5,
            "Friendship": "Общие интересы и взаимное уважение.",
            "FriendshipScore": 4,
            "Work": "Максимальная эффективность и внимание к деталям.",
            "WorkScore": 5,
            "Advice": "«Не забывайте о романтике в повседневности».",
        },
        "Libra": {
            "Elements": "Земля + Воздух",
            "Modes": "Фиксированный + Кардинальный",
            "Polarities": "Женская + Мужская",
            "Romance": "Телец ищет стабильность, Весы — гармонию.",
            "RomanceScore": 3,
            "Friendship": "Общение на эстетические темы.",
            "FriendshipScore": 4,
            "Work": "Весы предлагают идеи, Телец их реализует.",
            "WorkScore": 3,
            "Advice": "«Избегайте излишней критики».",
        },
        "Scorpio": {
            "Elements": "Земля + Вода",
            "Modes": "Фиксированный + Фиксированный",
            "Polarities": "Женская + Женская",
            "Romance": "Глубокие чувства и страсть.",
            "RomanceScore": 4,
            "Friendship": "Доверие нужно заслужить.",
            "FriendshipScore": 3,
            "Work": "Скорпион стратег, Телец исполнитель.",
            "WorkScore": 4,
            "Advice": "«Не допускайте ревности и скрытности».",
        },
        "Sagittarius": {
            "Elements": "Земля + Огонь",
            "Modes": "Фиксированный + Мутабельный",
            "Polarities": "Женская + Мужская",
            "Romance": "Телец хочет побыть дома, Стрелец — путешествий.",
            "RomanceScore": 2,
            "Friendship": "Возможна, если Стрелец замедлит темп.",
            "FriendshipScore": 3,
            "Work": "Разные цели: стабильность против авантюры.",
            "WorkScore": 2,
            "Advice": "«Научитесь ценить свободу друг друга».",
        },
        "Capricorn": {
            "Elements": "Земля + Земля",
            "Modes": "Фиксированный + Кардинальный",
            "Polarities": "Женская + Женская",
            "Romance": "Прочный союз с общими целями.",
            "RomanceScore": 5,
            "Friendship": "Взаимное уважение и поддержка.",
            "FriendshipScore": 5,
            "Work": "Идеальные партнеры для бизнеса.",
            "WorkScore": 5,
            "Advice": "«Добавьте эмоций в практичные отношения».",
        },
        "Aquarius": {
            "Elements": "Земля + Воздух",
            "Modes": "Фиксированный + Фиксированный",
            "Polarities": "Женская + Мужская",
            "Romance": "Телец консервативен, Водолей революционен.",
            "RomanceScore": 2,
            "Friendship": "Только если примут различия.",
            "FriendshipScore": 3,
            "Work": "Разные подходы: традиции против инноваций.",
            "WorkScore": 2,
            "Advice": "«Учитесь находить общий язык».",
        },
        "Pisces": {
            "Elements": "Земля + Вода",
            "Modes": "Фиксированный + Мутабельный",
            "Polarities": "Женская + Женская",
            "Romance": "Телец дает стабильность, Рыбы — романтику.",
            "RomanceScore": 4,
            "Friendship": "Гармония, если Телец проявит чуткость.",
            "FriendshipScore": 4,
            "Work": "Рыбы мечтают, Телец воплощает.",
            "WorkScore": 3,
            "Advice": "«Поддерживайте мечты Рыб, но оставайтесь реалистом».",
        },
    },
    "Gemini": {
        "Aries": {
            "Elements": "Воздух + Огонь",
            "Modes": "Мутабельный + Кардинальный",
            "Polarities": "Мужская + Мужская",
            "Romance": "Динамика и взаимное вдохновение.",
            "RomanceScore": 4,
            "Friendship": "Энергия и авантюры.",
            "FriendshipScore": 5,
            "Work": "Овен действует, Близнецы планируют.",
            "WorkScore": 4,
            "Advice": "«Избегайте конкуренции за лидерство».",
        },
        "Taurus": {
            "Elements": "Воздух + Земля",
            "Modes": "Мутабельный + Фиксированный",
            "Polarities": "Мужская + Женская",
            "Romance": "Телец ищет стабильность, Близнецы — разнообразие.",
            "RomanceScore": 2,
            "Friendship": "Общение возможно, если найти общие интересы.",
            "FriendshipScore": 3,
            "Work": "Близнецы импровизируют, Телец планирует.",
            "WorkScore": 2,
            "Advice": "«Уважайте потребность друг друга в предсказуемости и спонтанности».",
        },
        "Gemini": {
            "Elements": "Воздух + Воздух",
            "Modes": "Мутабельный + Мутабельный",
            "Polarities": "Мужская + Мужская",
            "Romance": "Интеллектуальная связь и веселье, но возможна поверхностность.",
            "RomanceScore": 4,
            "Friendship": "Идеальные партнеры для общения и приключений.",
            "FriendshipScore": 5,
            "Work": "Много идей, но недостаток фокуса.",
            "WorkScore": 3,
            "Advice": "«Ставьте четкие цели, чтобы избежать хаоса».",
        },
        "Cancer": {
            "Elements": "Воздух + Вода",
            "Modes": "Мутабельный + Кардинальный",
            "Polarities": "Мужская + Женская",
            "Romance": "Рак эмоционален, Близнецы рациональны.",
            "RomanceScore": 3,
            "Friendship": "Нуждаются в компромиссе между чувствами и логикой.",
            "FriendshipScore": 3,
            "Work": "Разные подходы: анализ против интуиции.",
            "WorkScore": 2,
            "Advice": "«Не обесценивайте эмоции Рака».",
        },
        "Leo": {
            "Elements": "Воздух + Огонь",
            "Modes": "Мутабельный + Фиксированный",
            "Polarities": "Мужская + Мужская",
            "Romance": "Яркие отношения с взаимным вдохновением.",
            "RomanceScore": 4,
            "Friendship": "Идеальный дуэт для творческих проектов.",
            "FriendshipScore": 5,
            "Work": "Лев лидирует, Близнецы генерируют идеи.",
            "WorkScore": 4,
            "Advice": "«Избегайте конкуренции за внимание».",
        },
        "Virgo": {
            "Elements": "Воздух + Земля",
            "Modes": "Мутабельный + Мутабельный",
            "Polarities": "Мужская + Женская",
            "Romance": "Близнецы общительны, Дева критична.",
            "RomanceScore": 3,
            "Friendship": "Интеллектуальная совместимость.",
            "FriendshipScore": 4,
            "Work": "Дева структурирует идеи Близнецов.",
            "WorkScore": 4,
            "Advice": "«Учитесь ценить внимание к деталям».",
        },
        "Libra": {
            "Elements": "Воздух + Воздух",
            "Modes": "Мутабельный + Кардинальный",
            "Polarities": "Мужкая + Мужская",
            "Romance": "Гармония в общении и романтике.",
            "RomanceScore": 5,
            "Friendship": "Идеальные собеседники и партнеры.",
            "FriendshipScore": 5,
            "Work": "Весы балансируют идеи Близнецов.",
            "WorkScore": 4,
            "Advice": "«Избегайте бесконечных дискуссий без действий».",
        },
        "Scorpio": {
            "Elements": "Воздух + Вода",
            "Modes": "Мутабельный + Фиксированный",
            "Polarities": "Мужская + Женская",
            "Romance": "Скорпион ревнив, Близнецы свободолюбивы.",
            "RomanceScore": 2,
            "Friendship": "Недоверие из-за скрытности Скорпиона.",
            "FriendshipScore": 2,
            "Work": "Скорпион стратег, Близнецы — коммуникатор.",
            "WorkScore": 3,
            "Advice": "«Работайте над открытостью и доверием».",
        },
        "Sagittarius": {
            "Elements": "Воздух + Огонь",
            "Modes": "Мутабельный + Мутабельный",
            "Polarities": "Мужская + Мужская",
            "Romance": "Идеальный союз для приключений и роста.",
            "RomanceScore": 5,
            "Friendship": "Оптимизм, юмор и общие интересы.",
            "FriendshipScore": 5,
            "Work": "Энергия и масштабные цели.",
            "WorkScore": 4,
            "Advice": "«Не увлекайтесь поверхностными задачами».",
        },
        "Capricorn": {
            "Elements": "Воздух + Земля",
            "Modes": "Мутабельный + Кардинальный",
            "Polarities": "Мужская + Женская",
            "Romance": "Козерог практичен, Близнецы непредсказуемы.",
            "RomanceScore": 2,
            "Friendship": "Возможна при общих целях.",
            "FriendshipScore": 3,
            "Work": "Козерог организует, Близнецы предлагают идеи.",
            "WorkScore": 3,
            "Advice": "«Научитесь сочетать креативность и дисциплину».",
        },
        "Aquarius": {
            "Elements": "Воздух + Воздух",
            "Modes": "Мутабельный + Фиксированный",
            "Polarities": "Мужская + Мужская",
            "Romance": "Инновации и свобода в отношениях.",
            "RomanceScore": 4,
            "Friendship": "Единство нестандартного мышления.",
            "FriendshipScore": 5,
            "Work": "Креативность и технологический подход.",
            "WorkScore": 5,
            "Advice": "«Не забывайте о эмоциональной стороне».",
        },
        "Pisces": {
            "Elements": "Воздух + Вода",
            "Modes": "Мутабельный + Мутабельный",
            "Polarities": "Мужская + Женская",
            "Romance": "Рыбы мечтательны, Близнецы рациональны.",
            "RomanceScore": 3,
            "Friendship": "Гармония, если Близнецы поддержат фантазии Рыб.",
            "FriendshipScore": 4,
            "Work": "Рыбы вдохновляют, Близнецы реализуют.",
            "WorkScore": 3,
            "Advice": "«Учитесь сочетать логику и интуицию».",
        },
    },
    "Cancer": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
    },
    "Leo": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
    },
    "Virgo": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
    },
    "Libra": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
    },
    "Scorpio": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
    },
    "Sagittarius": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
    },
    "Capricorn": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
    },
    "Aquarius": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
    },
    "Pisces": {
        "Aries": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Taurus": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Gemini": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Cancer": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Leo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Virgo": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Libra": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Scorpio": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Sagittarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Capricorn": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Aquarius": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
        "Pisces": {
            "Elements": "",
            "Modes": "",
            "Polarities": "",
            "Romance": "",
            "RomanceScore": "",
            "Friendship": "",
            "FriendshipScore": "",
            "Work": "",
            "WorkScore": "",
            "Advice": "",
        },
    },
}